from src.agents.reporting.deterministic_report_generator import (
    DeterministicReportGenerator,
)
from src.agents.reporting.report_generator import ReportGenerator
from src.models.assessment_analysis import AssessmentAnalysis
from src.models.assessment_status import AssessmentStatus


def test_deterministic_report_generator_implements_contract():

    generator = DeterministicReportGenerator()

    assert isinstance(generator, ReportGenerator)


def test_deterministic_report_generator_preserves_analysis_data():

    analysis = AssessmentAnalysis(
        position_id="POS001",
        assessment_status=AssessmentStatus.CRITICAL,
        key_findings=[
            "Revenue deterioration detected.",
            "Negative EBITDA detected.",
        ],
        risk_factors=[
            "Negative EBITDA detected.",
        ],
        limitations=[
            "EBITDA Inventory Contribution",
        ],
    )

    generator = DeterministicReportGenerator()

    report = generator.generate(analysis)

    assert report.position_id == analysis.position_id
    assert report.assessment_status == analysis.assessment_status

    # Findings generated by the AnalysisAgent must be
    # propagated unchanged to the report.
    assert report.findings == analysis.key_findings

    # Limitations generated by the AnalysisAgent must be
    # propagated unchanged to the report.
    assert report.limitations == analysis.limitations

    # The deterministic generator creates only the summary.
    assert report.executive_summary == (
        "The credit assessment is classified as critical."
    )


def test_deterministic_report_generator_generates_normal_summary():

    analysis = AssessmentAnalysis(
        position_id="POS001",
        assessment_status=AssessmentStatus.NORMAL,
        key_findings=[],
        risk_factors=[],
        limitations=[],
    )

    report = DeterministicReportGenerator().generate(analysis)

    assert report.position_id == analysis.position_id
    assert report.assessment_status == analysis.assessment_status
    assert report.findings == []
    assert report.limitations == []

    assert report.executive_summary == (
        "The credit assessment is classified as normal."
    )


def test_deterministic_report_generator_generates_attention_summary():

    analysis = AssessmentAnalysis(
        position_id="POS001",
        assessment_status=AssessmentStatus.ATTENTION,
        key_findings=[
            "Revenue deterioration detected.",
        ],
        risk_factors=[
            "Revenue deterioration detected.",
        ],
        limitations=[],
    )

    report = DeterministicReportGenerator().generate(analysis)

    assert report.position_id == analysis.position_id
    assert report.assessment_status == analysis.assessment_status

    assert report.findings == analysis.key_findings
    assert report.limitations == analysis.limitations

    assert report.executive_summary == (
        "The credit assessment requires attention."
    )