import re

from src.agents.reporting.report_generator import ReportGenerator
from src.llm.client import LLMClient
from src.llm.prompt_builder import ReportPromptBuilder
from src.models.analysis_finding import AnalysisFinding
from src.models.assessment_analysis import AssessmentAnalysis
from src.models.report import Report, ReportFindingGroup


class LLMReportGenerator(ReportGenerator):
    """
    Report generator based on an abstract LLM client.

    The LLM is used exclusively to generate the executive narrative.

    The deterministic assessment remains the source of truth for:

    - assessment status;
    - findings;
    - finding severity;
    - finding categories;
    - limitations.

    The LLM does not perform assessment logic and does not modify
    any deterministic assessment information.
    """

    _INDICATOR_PATTERNS = (
        re.compile(r"€\s*-?\d[\d,.]*"),
        re.compile(r"-?\d[\d,.]*\s*%"),
        re.compile(r"-?\d[\d,.]*\s*x\b", re.IGNORECASE),
    )

    def __init__(
        self,
        llm_client: LLMClient,
        prompt_builder: ReportPromptBuilder | None = None,
        require_indicator_values: bool = False,
    ) -> None:
        self.llm_client = llm_client
        self.prompt_builder = (
            prompt_builder if prompt_builder is not None else ReportPromptBuilder()
        )
        self.require_indicator_values = require_indicator_values

    def generate(
        self,
        analysis: AssessmentAnalysis,
    ) -> Report:
        """
        Generate a report from a deterministic assessment.

        The prompt is created by the dedicated prompt builder.
        The LLM generates only the executive narrative.

        All structured assessment information is taken directly
        from the deterministic assessment.
        """

        prompt = self.prompt_builder.build(analysis)

        response = self.llm_client.generate(prompt)

        validated_response = self._validate_response(response)

        if self.require_indicator_values:
            validated_response = self._ensure_indicator_values(
                narrative=validated_response,
                findings=analysis.key_findings,
            )

        executive_summary = self._build_executive_summary(
            analysis=analysis,
            narrative=validated_response,
        )

        findings_by_category = self._group_findings_by_category(
            analysis.key_findings,
        )

        return Report(
            position_id=analysis.position_id,
            assessment_status=analysis.assessment_status,
            executive_summary=executive_summary,
            findings_by_category=findings_by_category,
            limitations=analysis.limitations,
        )

    # ============================================================
    # Executive summary
    # ============================================================

    @staticmethod
    def _build_executive_summary(
        analysis: AssessmentAnalysis,
        narrative: str,
    ) -> str:
        """
        Combine the deterministic assessment status with the
        LLM-generated narrative.

        The status is deliberately added by the application rather
        than generated by the LLM.
        """

        return f"Assessment status: {analysis.assessment_status.value}.\n{narrative}"

    # ============================================================
    # Indicator grounding
    # ============================================================

    @classmethod
    def _extract_indicator_values(cls, findings: list[AnalysisFinding]) -> list[str]:
        """Extract supplied numerical indicator values from deterministic findings."""
        values: list[str] = []

        for finding in findings:
            for pattern in cls._INDICATOR_PATTERNS:
                for match in pattern.findall(finding.text):
                    normalized = " ".join(match.split())
                    if normalized not in values:
                        values.append(normalized)

        return values

    @classmethod
    def _ensure_indicator_values(
        cls,
        narrative: str,
        findings: list[AnalysisFinding],
    ) -> str:
        """
        Ensure local-LLM narratives retain deterministic indicator values.

        Missing values are appended verbatim from the deterministic
        findings. This is a grounding safeguard, not new LLM-generated
        assessment content.
        """
        indicator_values = cls._extract_indicator_values(findings)
        missing_values = [
            value for value in indicator_values if value not in narrative
        ]

        if not missing_values:
            return narrative

        values_text = ", ".join(missing_values)
        return (
            f"{narrative.rstrip()} "
            f"Reported indicator values: {values_text}."
        )

    # ============================================================
    # Finding grouping
    # ============================================================

    @staticmethod
    def _group_findings_by_category(
        findings: list[AnalysisFinding],
    ) -> list[ReportFindingGroup]:
        """
        Group deterministic findings by category.

        The operation is completely independent of the LLM.
        The original finding order is preserved.
        """

        grouped: dict[str, list[AnalysisFinding]] = {}

        for finding in findings:
            grouped.setdefault(
                finding.category,
                [],
            ).append(finding)

        return [
            ReportFindingGroup(
                category=category,
                findings=category_findings,
            )
            for category, category_findings in grouped.items()
        ]

    # ============================================================
    # LLM response validation
    # ============================================================

    @staticmethod
    def _validate_response(
        response: str,
    ) -> str:
        """
        Validate the LLM-generated executive narrative.

        The generator currently performs structural validation only.
        Semantic assessment validation is intentionally unnecessary
        because the LLM does not own the deterministic assessment.
        """

        if not response or not response.strip():
            raise ValueError("LLM returned an empty response")

        return response.strip()
