from src.agents.reporting.report_generator import ReportGenerator
from src.llm.client import LLMClient
from src.llm.prompt_builder import ReportPromptBuilder
from src.models.analysis_finding import AnalysisFinding
from src.models.assessment_analysis import AssessmentAnalysis
from src.models.report import Report, ReportFindingGroup


class LLMReportGenerator(ReportGenerator):
    """
    Report generator based on an abstract LLM client.

    The LLM is used exclusively to generate the executive narrative.

    The deterministic assessment remains the source of truth for:

    - assessment status;
    - findings;
    - finding severity;
    - finding categories;
    - limitations.

    The LLM does not perform assessment logic and does not modify
    any deterministic assessment information.
    """

    def __init__(
        self,
        llm_client: LLMClient,
        prompt_builder: ReportPromptBuilder | None = None,
    ) -> None:
        self.llm_client = llm_client
        self.prompt_builder = (
            prompt_builder
            if prompt_builder is not None
            else ReportPromptBuilder()
        )

    def generate(
        self,
        analysis: AssessmentAnalysis,
    ) -> Report:
        """
        Generate a report from a deterministic assessment.

        The prompt is created by the dedicated prompt builder.
        The LLM generates only the executive narrative.

        All structured assessment information is taken directly
        from the deterministic assessment.
        """

        prompt = self.prompt_builder.build(analysis)

        response = self.llm_client.generate(prompt)

        validated_response = self._validate_response(response)

        executive_summary = self._build_executive_summary(
            analysis=analysis,
            narrative=validated_response,
        )

        findings_by_category = (
            self._group_findings_by_category(
                analysis.key_findings,
            )
        )

        return Report(
            position_id=analysis.position_id,
            assessment_status=analysis.assessment_status,
            executive_summary=executive_summary,
            findings_by_category=findings_by_category,
            limitations=analysis.limitations,
        )

    # ============================================================
    # Executive summary
    # ============================================================

    @staticmethod
    def _build_executive_summary(
        analysis: AssessmentAnalysis,
        narrative: str,
    ) -> str:
        """
        Combine the deterministic assessment status with the
        LLM-generated narrative.

        The status is deliberately added by the application rather
        than generated by the LLM.
        """

        return (
            f"Assessment status: "
            f"{analysis.assessment_status.value}.\n"
            f"{narrative}"
        )

    # ============================================================
    # Finding grouping
    # ============================================================

    @staticmethod
    def _group_findings_by_category(
        findings: list[AnalysisFinding],
    ) -> list[ReportFindingGroup]:
        """
        Group deterministic findings by category.

        The operation is completely independent of the LLM.
        The original finding order is preserved.
        """

        grouped: dict[str, list[AnalysisFinding]] = {}

        for finding in findings:
            grouped.setdefault(
                finding.category,
                [],
            ).append(finding)

        return [
            ReportFindingGroup(
                category=category,
                findings=category_findings,
            )
            for category, category_findings in grouped.items()
        ]

    # ============================================================
    # LLM response validation
    # ============================================================

    @staticmethod
    def _validate_response(
        response: str,
    ) -> str:
        """
        Validate the LLM-generated executive narrative.

        The generator currently performs structural validation only.
        Semantic assessment validation is intentionally unnecessary
        because the LLM does not own the deterministic assessment.
        """

        if not response or not response.strip():
            raise ValueError(
                "LLM returned an empty response"
            )

        return response.strip()