import pytest

from src.agents.reporting.llm_report_generator import (
    LLMReportGenerator,
)
from src.agents.workflow.workflow_factory import (
    create_default_assessment_workflow,
)
from src.llm.mock_client import MockLLMClient
from src.models.position import CreditPosition
from src.rules.base.status import RuleStatus


# ============================================================
# Fixtures
# ============================================================


@pytest.fixture
def risk_position() -> CreditPosition:
    """
    Return a position designed to produce a non-normal
    deterministic assessment.
    """
    return CreditPosition(
        position_id="TEST_POSITION",
        revenue_growth=-0.15,
        ebitda=-50000,
        profit_loss=-50000,
        ebitda_margin=-0.05,
        pfn_to_ebitda=6.0,
        interest_expense=40000,
    )


@pytest.fixture
def normal_position() -> CreditPosition:
    """
    Return a position expected to produce a normal assessment.
    """
    return CreditPosition(
        position_id="TEST_NORMAL_POSITION",
        revenue_growth=0.05,
        ebitda=250000,
        profit_loss=100000,
        ebitda_margin=0.15,
        pfn_to_ebitda=2.0,
        interest_expense=10000,
    )


# ============================================================
# Helpers
# ============================================================


def report_findings_by_category(report):
    """
    Return report findings grouped by category.
    """
    return {
        group.category: group.findings
        for group in report.findings_by_category
    }


def analysis_findings_by_category(analysis):
    """
    Return analysis findings grouped by category.
    """
    findings_by_category = {}

    for finding in analysis.key_findings:
        findings_by_category.setdefault(
            finding.category,
            [],
        ).append(finding)

    return findings_by_category


def deterministic_findings(assessment):
    """
    Return findings generated by deterministic rules.
    """
    return [
        finding
        for finding in assessment.findings
        if finding.result.status == RuleStatus.TRIGGERED
    ]


def normalize_prompt(prompt: str) -> str:
    """
    Normalize prompt text.
    """
    return " ".join(prompt.lower().split())


def assert_prompt_contains_any(
    prompt: str,
    alternatives: tuple[str, ...],
) -> None:
    """
    Assert that at least one semantic alternative exists.
    """
    normalized_prompt = normalize_prompt(prompt)

    assert any(
        alternative.lower() in normalized_prompt
        for alternative in alternatives
    ), (
        f"None of {alternatives!r} found in prompt."
    )


def assert_deterministic_information_is_preserved(result):
    """
    Verify that the LLM does not alter deterministic data.
    """

    assert result.assessment is not None
    assert result.analysis is not None
    assert result.report is not None

    assert (
        result.analysis.assessment_status
        == result.assessment.status
    )

    assert (
        result.report.assessment_status
        == result.assessment.status
    )

    assert (
        report_findings_by_category(result.report)
        == analysis_findings_by_category(result.analysis)
    )

    assert (
        result.report.limitations
        == result.analysis.limitations
    )


def make_valid_llm_response():
    """
    Generate a valid LLM narrative response.

    The LLM is responsible only for natural language generation.
    The deterministic assessment status is not part of the
    generated response contract.
    """

    return (
        "The analysis highlights relevant financial risk "
        "factors affecting the company's credit profile. "
        "The observed indicators suggest areas requiring "
        "continuous monitoring and management attention."
    )


# ============================================================
# End-to-end deterministic workflow
# ============================================================


def test_credit_assessment_end_to_end(
    risk_position,
):

    workflow = create_default_assessment_workflow(
        use_llm=False,
    )

    result = workflow.run(
        risk_position,
    )

    assert result.assessment is not None
    assert result.analysis is not None
    assert result.report is not None

    assert (
        result.assessment.position_id
        == risk_position.position_id
    )

    assert (
        result.analysis.position_id
        == risk_position.position_id
    )

    assert (
        result.report.position_id
        == risk_position.position_id
    )

    assert result.assessment.status is not None

    assert (
        result.analysis.assessment_status
        == result.assessment.status
    )

    assert (
        result.report.assessment_status
        == result.assessment.status
    )

    assert result.report.executive_summary

    assert isinstance(
        result.report.limitations,
        list,
    )


def test_credit_assessment_propagates_findings_through_pipeline(
    risk_position,
):

    workflow = create_default_assessment_workflow(
        use_llm=False,
    )

    result = workflow.run(
        risk_position,
    )

    assessment = result.assessment
    analysis = result.analysis
    report = result.report

    assert assessment.findings

    triggered_findings = deterministic_findings(
        assessment,
    )

    assert triggered_findings

    expected_findings = [
        (
            finding.result.category,
            finding.comment.text,
        )
        for finding in triggered_findings
    ]

    actual_analysis_findings = [
        (
            finding.category,
            finding.text,
        )
        for finding in analysis.key_findings
    ]

    assert actual_analysis_findings == expected_findings

    assert (
        report_findings_by_category(report)
        == analysis_findings_by_category(analysis)
    )

    assert (
        report.limitations
        == analysis.limitations
    )


# ============================================================
# LLM workflow
# ============================================================


def test_llm_workflow_uses_primary_generator(
    risk_position,
):

    llm_client = MockLLMClient(
        response=make_valid_llm_response(),
    )

    workflow = create_default_assessment_workflow(
        use_llm=True,
        llm_client=llm_client,
    )

    assert isinstance(
        workflow.reporting_agent.report_generator,
        LLMReportGenerator,
    )

    result = workflow.run(
        risk_position,
    )

    assert result.assessment is not None
    assert result.analysis is not None
    assert result.report is not None

    assert result.report.executive_summary

    assert (
        workflow.reporting_agent.last_generator_used
        == "PRIMARY"
    )

    assert workflow.reporting_agent.last_error is None


def test_credit_assessment_llm_workflow(
    risk_position,
):

    llm_client = MockLLMClient(
        response=make_valid_llm_response(),
    )

    workflow = create_default_assessment_workflow(
        use_llm=True,
        llm_client=llm_client,
    )

    result = workflow.run(
        risk_position,
    )

    assert isinstance(
        workflow.reporting_agent.report_generator,
        LLMReportGenerator,
    )

    assert_deterministic_information_is_preserved(
        result,
    )

    assert result.report.executive_summary

    assert (
        workflow.reporting_agent.last_generator_used
        == "PRIMARY"
    )

    assert workflow.reporting_agent.last_error is None


def test_llm_workflow_sends_prompt_to_llm_client(
    risk_position,
):

    llm_client = MockLLMClient(
        response=make_valid_llm_response(),
    )

    workflow = create_default_assessment_workflow(
        use_llm=True,
        llm_client=llm_client,
    )

    workflow.run(
        risk_position,
    )

    assert llm_client.last_prompt is not None
    assert llm_client.last_prompt.strip()


# ============================================================
# LLM prompt
# ============================================================


def test_llm_prompt_contains_deterministic_assessment_data(
    risk_position,
):

    deterministic_workflow = create_default_assessment_workflow(
        use_llm=False,
    )

    deterministic_result = deterministic_workflow.run(
        risk_position,
    )

    llm_client = MockLLMClient(
        response=make_valid_llm_response(),
    )

    workflow = create_default_assessment_workflow(
        use_llm=True,
        llm_client=llm_client,
    )

    workflow.run(
        risk_position,
    )

    prompt = llm_client.last_prompt

    assert prompt is not None

    normalized_prompt = normalize_prompt(prompt)

    for finding in deterministic_result.analysis.key_findings:
        assert finding.text.lower() in normalized_prompt

    for finding in deterministic_result.analysis.risk_factors:
        assert finding.text.lower() in normalized_prompt


def test_llm_prompt_contains_safety_constraints(
    risk_position,
):

    llm_client = MockLLMClient(
        response=make_valid_llm_response(),
    )

    workflow = create_default_assessment_workflow(
        use_llm=True,
        llm_client=llm_client,
    )

    workflow.run(
        risk_position,
    )

    prompt = llm_client.last_prompt

    assert prompt is not None

    assert_prompt_contains_any(
        prompt,
        (
            "deterministic assessment",
            "rule-based assessment",
            "deterministic rule",
        ),
    )

    assert_prompt_contains_any(
        prompt,
        (
            "only",
            "exclusively",
            "solely",
        ),
    )

    assert_prompt_contains_any(
        prompt,
        (
            "do not invent",
            "do not fabricate",
            "do not add facts",
        ),
    )

    assert_prompt_contains_any(
        prompt,
        (
            "do not modify",
            "do not alter",
            "do not override",
        ),
    )

# ============================================================
# LLM cannot modify deterministic assessment
# ============================================================


def test_llm_cannot_change_deterministic_assessment(
    risk_position,
):

    deterministic_workflow = create_default_assessment_workflow(
        use_llm=False,
    )

    deterministic_result = deterministic_workflow.run(
        risk_position,
    )

    expected_status = deterministic_result.assessment.status

    llm_client = MockLLMClient(
        response=(
            "The company shows severe financial deterioration "
            "and requires continuous monitoring."
        ),
    )

    workflow = create_default_assessment_workflow(
        use_llm=True,
        llm_client=llm_client,
    )

    result = workflow.run(
        risk_position,
    )

    assert (
        result.assessment.status
        == expected_status
    )

    assert (
        result.analysis.assessment_status
        == expected_status
    )

    assert (
        result.report.assessment_status
        == expected_status
    )

    assert result.report.executive_summary

    assert_deterministic_information_is_preserved(
        result,
    )


# ============================================================
# LLM cannot replace deterministic findings
# ============================================================


def test_llm_cannot_replace_deterministic_findings(
    risk_position,
):

    llm_client = MockLLMClient(
        response=(
            "The company has a strong financial profile "
            "despite some relevant observations."
        ),
    )

    workflow = create_default_assessment_workflow(
        use_llm=True,
        llm_client=llm_client,
    )

    result = workflow.run(
        risk_position,
    )

    report_by_category = report_findings_by_category(
        result.report,
    )

    analysis_by_category = analysis_findings_by_category(
        result.analysis,
    )

    assert (
        report_by_category
        == analysis_by_category
    )

    deterministic_findings = [
        finding.text
        for finding in result.analysis.key_findings
    ]

    for finding in deterministic_findings:
        assert finding in [
            item.text
            for group in result.report.findings_by_category
            for item in group.findings
        ]


# ============================================================
# LLM cannot replace deterministic limitations
# ============================================================


def test_llm_cannot_replace_deterministic_limitations(
    risk_position,
):

    llm_client = MockLLMClient(
        response=(
            "All available financial information has been "
            "considered and summarized."
        ),
    )

    workflow = create_default_assessment_workflow(
        use_llm=True,
        llm_client=llm_client,
    )

    result = workflow.run(
        risk_position,
    )

    assert (
        result.report.limitations
        == result.analysis.limitations
    )


# ============================================================
# LLM response validation
# ============================================================


def test_llm_response_is_rejected_when_empty(
    risk_position,
):

    llm_client = MockLLMClient(
        response="   ",
    )

    workflow = create_default_assessment_workflow(
        use_llm=True,
        llm_client=llm_client,
    )

    result = workflow.run(
        risk_position,
    )

    assert result.report is not None

    assert (
        workflow.reporting_agent.last_generator_used
        == "FALLBACK"
    )

    assert (
        workflow.reporting_agent.last_error
        ==
        (
            "LLM report generation failed: "
            "LLM returned an empty response"
        )
    )

    assert (
        result.report.assessment_status
        == result.assessment.status
    )


def test_llm_response_content_is_preserved(
    risk_position,
):

    response = (
        "This narrative was generated by the LLM "
        "to summarize the available information."
    )

    llm_client = MockLLMClient(
        response=response,
    )

    workflow = create_default_assessment_workflow(
        use_llm=True,
        llm_client=llm_client,
    )

    result = workflow.run(
        risk_position,
    )

    assert (
        workflow.reporting_agent.last_generator_used
        == "PRIMARY"
    )

    assert (
        response
        in result.report.executive_summary
    )

    assert (
        result.report.executive_summary.startswith(
            "Assessment status:"
        )
    )


def test_llm_response_whitespace_is_normalized(
    risk_position,
):

    response = (
        "   Generated narrative content "
        "with surrounding spaces.   "
    )

    expected_response = (
        "Generated narrative content "
        "with surrounding spaces."
    )

    llm_client = MockLLMClient(
        response=response,
    )

    workflow = create_default_assessment_workflow(
        use_llm=True,
        llm_client=llm_client,
    )

    result = workflow.run(
        risk_position,
    )

    assert (
        expected_response
        in result.report.executive_summary
    )

    assert (
        result.report.executive_summary.startswith(
            "Assessment status:"
        )
    )


def test_llm_accepts_response_without_assessment_status(
    risk_position,
):

    response = (
        "The generated narrative focuses on "
        "financial indicators and relevant observations."
    )

    llm_client = MockLLMClient(
        response=response,
    )

    workflow = create_default_assessment_workflow(
        use_llm=True,
        llm_client=llm_client,
    )

    result = workflow.run(
        risk_position,
    )

    assert (
        workflow.reporting_agent.last_generator_used
        == "PRIMARY"
    )

    assert workflow.reporting_agent.last_error is None

    assert (
        response
        in result.report.executive_summary
    )

    assert (
        result.report.executive_summary.startswith(
            "Assessment status:"
        )
    )


# ============================================================
# LLM failure and deterministic fallback
# ============================================================


def test_credit_assessment_falls_back_to_deterministic_report_when_llm_fails(
    risk_position,
):

    llm_client = MockLLMClient(
        error=RuntimeError(
            "LLM service unavailable",
        ),
    )

    workflow = create_default_assessment_workflow(
        use_llm=True,
        llm_client=llm_client,
    )

    result = workflow.run(
        risk_position,
    )

    assert result.assessment is not None
    assert result.analysis is not None
    assert result.report is not None

    assert (
        result.assessment.status
        == result.analysis.assessment_status
    )

    assert (
        result.report.assessment_status
        == result.assessment.status
    )

    assert result.report.executive_summary

    assert (
        workflow.reporting_agent.last_generator_used
        == "FALLBACK"
    )

    assert (
        workflow.reporting_agent.last_error
        ==
        "LLM service is temporarily unavailable."
    )

    assert_deterministic_information_is_preserved(
        result,
    )


# ============================================================
# NOT_EVALUABLE rules
# ============================================================


def test_not_evaluable_rules_do_not_generate_findings(
    normal_position,
):

    workflow = create_default_assessment_workflow(
        use_llm=False,
    )

    result = workflow.run(
        normal_position,
    )

    not_evaluable_results = [
        rule_result
        for rule_result in result.assessment.rule_results
        if rule_result.status
        == RuleStatus.NOT_EVALUABLE
    ]

    assert not_evaluable_results

    not_evaluable_rule_ids = {
        rule_result.rule_id
        for rule_result in not_evaluable_results
    }

    finding_rule_ids = {
        finding.result.rule_id
        for finding in result.assessment.findings
    }

    assert finding_rule_ids.isdisjoint(
        not_evaluable_rule_ids,
    )

    assert result.analysis.key_findings == []

    assert (
        report_findings_by_category(result.report)
        == {}
    )
