from dataclasses import MISSING, fields
from types import UnionType
from typing import Any, get_args, get_origin, get_type_hints

import streamlit as st

from src.models.position import CreditPosition

# ============================================================
# CreditPosition Introspection
# ============================================================

def get_credit_position_fields():
    """
    Return the fields defined by the CreditPosition dataclass.

    CreditPosition remains the source of truth for the input schema.
    """

    return fields(CreditPosition)


def get_credit_position_type_hints() -> dict[str, Any]:
    """
    Return resolved type annotations for CreditPosition.
    """

    return get_type_hints(CreditPosition)


def get_field_default(field) -> Any:
    """
    Return the default defined by the dataclass.

    If the field has no explicit default, return None.
    """

    if field.default is not MISSING:
        return field.default

    if field.default_factory is not MISSING:
        return field.default_factory()

    return None


# ============================================================
# Type Introspection Helpers
# ============================================================

def unwrap_optional(
    field_type: Any,
) -> tuple[Any, bool]:
    """
    Resolve Optional / Union-with-None annotations.
    """

    origin = get_origin(field_type)
    args = get_args(field_type)

    if origin is UnionType:
        non_none_types = [
            argument
            for argument in args
            if argument is not type(None)
        ]

        if len(non_none_types) == 1:
            return non_none_types[0], True

    if args and type(None) in args:
        non_none_types = [
            argument
            for argument in args
            if argument is not type(None)
        ]

        if len(non_none_types) == 1:
            return non_none_types[0], True

    return field_type, False


# ============================================================
# Field Presentation
# ============================================================

def format_field_label(
    field_name: str,
) -> str:

    special_terms = {
        "ebitda": "EBITDA",
        "nfp": "nfp",
        "id": "ID",
    }

    words = field_name.split("_")

    formatted_words = []

    for word in words:
        if word.lower() in special_terms:
            formatted_words.append(
                special_terms[word.lower()]
            )
        else:
            formatted_words.append(
                word.capitalize()
            )

    return " ".join(formatted_words)


def format_field_description(
    field_name: str,
) -> str:

    descriptions = {
        "position_id": (
            "Unique identifier of the credit position."
        ),

        "revenue": (
            "Total company revenue."
        ),

        "change_in_finished_goods_inventory": (
            "Change in finished goods inventory."
        ),

        "operating_grants": (
            "Operating grants received by the company."
        ),

        "net_purchases": (
            "Net purchases of raw materials and goods."
        ),

        "change_in_raw_materials_inventory": (
            "Change in raw materials inventory."
        ),

        "costs_for_services_and_third_party_assets": (
            "Costs related to services and third-party assets."
        ),

        "personnel_costs": (
            "Personnel and employee-related costs."
        ),

        "depreciation_tangible_assets": (
            "Depreciation of tangible fixed assets."
        ),

        "working_capital_impairments": (
            "Impairments related to working capital."
        ),

        "operating_provisions": (
            "Operating provisions and related adjustments."
        ),

        "other_income_expenses_balance": (
            "Net balance of other operating income and expenses."
        ),

        "operating_value_added": (
            "Derived operating value added."
        ),

        "gross_operating_margin": (
            "Gross operating margin generated by the company."
        ),

        "net_operating_margin": (
            "Net operating margin after operating costs."
        ),

        "ebitda": (
            "Earnings before interest, taxes, "
            "depreciation and amortization."
        ),

        "profit_loss": (
            "Reported profit or loss for the company."
        ),

        "ebitda_margin": (
            "EBITDA expressed as a percentage of revenue."
        ),

        "ebitda_inventory_contribution": (
            "Contribution of inventory changes to EBITDA."
        ),

        "nfp_to_ebitda": (
            "Net financial position relative to EBITDA; "
            "a leverage indicator."
        ),

        "interest_expense": (
            "Financial expense related to interest."
        ),

        "revenue_growth": (
            "Year-over-year change in company revenue."
        ),
    }

    return descriptions.get(
        field_name,
        f"Input value for {format_field_label(field_name)}.",
    )


def format_field_value(
    field_name: str,
    value: Any,
) -> str:

    if value is None:
        return "Not available"

    if field_name == "position_id":
        return str(value)

    if field_name in {
        "revenue_growth",
        "ebitda_margin",
    }:
        return f"{float(value):.1%}"

    if field_name in {
        "revenue",
        "change_in_finished_goods_inventory",
        "operating_grants",
        "net_purchases",
        "change_in_raw_materials_inventory",
        "costs_for_services_and_third_party_assets",
        "personnel_costs",
        "depreciation_tangible_assets",
        "working_capital_impairments",
        "operating_provisions",
        "other_income_expenses_balance",
        "operating_value_added",
        "gross_operating_margin",
        "net_operating_margin",
        "ebitda",
        "profit_loss",
        "ebitda_inventory_contribution",
        "interest_expense",
    }:
        return f"€{float(value):,.0f}"

    if field_name == "nfp_to_ebitda":
        return f"{float(value):.2f}x"

    if isinstance(value, float):
        return f"{value:,.4f}"

    return str(value)


def get_field_unit(
    field_name: str,
) -> str:

    units = {
        "position_id": "Identifier",

        "revenue_growth": "%",
        "ebitda_margin": "%",

        "revenue": "EUR",
        "change_in_finished_goods_inventory": "EUR",
        "operating_grants": "EUR",
        "net_purchases": "EUR",
        "change_in_raw_materials_inventory": "EUR",
        "costs_for_services_and_third_party_assets": "EUR",
        "personnel_costs": "EUR",
        "depreciation_tangible_assets": "EUR",
        "working_capital_impairments": "EUR",
        "operating_provisions": "EUR",
        "other_income_expenses_balance": "EUR",
        "operating_value_added": "EUR",
        "gross_operating_margin": "EUR",
        "net_operating_margin": "EUR",
        "ebitda": "EUR",
        "profit_loss": "EUR",
        "ebitda_inventory_contribution": "EUR",
        "interest_expense": "EUR",

        "nfp_to_ebitda": "x",
    }

    return units.get(
        field_name,
        "",
    )


# ============================================================
# Scenario / Position Data Presentation
# ============================================================

def build_scenario_data_table(
    position: CreditPosition,
) -> list[dict[str, str]]:

    rows = []

    for field in fields(position):

        field_name = field.name

        value = getattr(
            position,
            field_name,
        )

        rows.append(
            {
                "Financial Indicator": format_field_label(
                    field_name
                ),
                "Value": format_field_value(
                    field_name,
                    value,
                ),
                "Unit": get_field_unit(
                    field_name
                ),
                "Description": format_field_description(
                    field_name
                ),
            }
        )

    return rows


def display_position_table(
    position: CreditPosition,
) -> None:

    position_data = build_scenario_data_table(
        position
    )

    st.dataframe(
        position_data,
        use_container_width=True,
        hide_index=True,
        column_config={
            "Financial Indicator": st.column_config.TextColumn(
                "Financial Indicator",
                width="medium",
            ),
            "Value": st.column_config.TextColumn(
                "Value",
                width="medium",
            ),
            "Unit": st.column_config.TextColumn(
                "Unit",
                width="small",
            ),
            "Description": st.column_config.TextColumn(
                "What it represents",
                width="large",
            ),
        },
    )


# ============================================================
# Manual Input
# ============================================================

def create_optional_numeric_field(
    field_name: str,
    label: str,
    resolved_type: Any,
    default: Any,
) -> Any:

    provided_key = (
        f"credit_position_{field_name}_provided"
    )

    value_key = (
        f"credit_position_{field_name}_value"
    )

    provided = st.checkbox(
        f"Provide {label}",
        value=default is not None,
        key=provided_key,
    )

    if not provided:
        return None

    if resolved_type is int:

        return st.number_input(
            label,
            value=(
                int(default)
                if default is not None
                else 0
            ),
            step=1,
            key=value_key,
        )

    if resolved_type is float:

        return st.number_input(
            label,
            value=(
                float(default)
                if default is not None
                else 0.0
            ),
            step=0.01,
            format="%.4f",
            key=value_key,
        )

    raise TypeError(
        f"Unsupported optional numeric type: "
        f"{field_name} -> {resolved_type}"
    )


def create_streamlit_field(
    field,
    field_type: Any,
) -> Any:

    field_name = field.name

    label = format_field_label(
        field_name
    )

    default = get_field_default(
        field
    )

    resolved_type, is_optional = (
        unwrap_optional(field_type)
    )

    description = format_field_description(
        field_name
    )

    if resolved_type is str and not is_optional:

        st.caption(description)

        return st.text_input(
            label,
            value=(
                ""
                if default is None
                else str(default)
            ),
            key=f"credit_position_{field_name}",
        )

    if resolved_type is str and is_optional:

        provided = st.checkbox(
            f"Provide {label}",
            value=default is not None,
            key=(
                f"credit_position_{field_name}_provided"
            ),
        )

        if not provided:
            return None

        st.caption(description)

        return st.text_input(
            label,
            value=(
                ""
                if default is None
                else str(default)
            ),
            key=(
                f"credit_position_{field_name}_value"
            ),
        )

    if resolved_type is int and not is_optional:

        st.caption(description)

        return st.number_input(
            label,
            value=(
                0
                if default is None
                else int(default)
            ),
            step=1,
            key=f"credit_position_{field_name}",
        )

    if resolved_type is float and not is_optional:

        st.caption(description)

        return st.number_input(
            label,
            value=(
                0.0
                if default is None
                else float(default)
            ),
            step=0.01,
            format="%.4f",
            key=f"credit_position_{field_name}",
        )

    if (
        is_optional
        and resolved_type in {int, float}
    ):

        return create_optional_numeric_field(
            field_name=field_name,
            label=label,
            resolved_type=resolved_type,
            default=default,
        )

    raise TypeError(
        f"Unsupported CreditPosition field type: "
        f"{field_name} -> {field_type}"
    )


def build_credit_position_from_ui() -> dict[str, Any]:

    model_fields = (
        get_credit_position_fields()
    )

    type_hints = (
        get_credit_position_type_hints()
    )

    position_data: dict[str, Any] = {}

    columns = st.columns(3)

    for index, field in enumerate(
        model_fields
    ):

        with columns[
            index % len(columns)
        ]:

            position_data[field.name] = (
                create_streamlit_field(
                    field=field,
                    field_type=type_hints[
                        field.name
                    ],
                )
            )

    return position_data

