from dataclasses import MISSING, fields
from types import UnionType
from typing import Any, get_args, get_origin, get_type_hints

import streamlit as st

from src.models.position import CreditPosition


# ============================================================
# CreditPosition Introspection
# ============================================================


def get_credit_position_fields():
    """
    Return the fields defined by the CreditPosition dataclass.

    CreditPosition remains the source of truth for the input schema.
    """

    return fields(CreditPosition)


def get_credit_position_type_hints() -> dict[str, Any]:
    """
    Return resolved type annotations for CreditPosition.
    """

    return get_type_hints(CreditPosition)


def get_field_default(field) -> Any:
    """
    Return the default defined by the dataclass.

    If the field has no explicit default, return None.
    """

    if field.default is not MISSING:
        return field.default

    if field.default_factory is not MISSING:
        return field.default_factory()

    return None


# ============================================================
# Type Introspection Helpers
# ============================================================


def unwrap_optional(
    field_type: Any,
) -> tuple[Any, bool]:
    """
    Resolve Optional / Union-with-None annotations.
    """

    origin = get_origin(field_type)
    args = get_args(field_type)

    if origin is UnionType:

        non_none_types = [
            argument
            for argument in args
            if argument is not type(None)
        ]

        if len(non_none_types) == 1:
            return non_none_types[0], True

    if args and type(None) in args:

        non_none_types = [
            argument
            for argument in args
            if argument is not type(None)
        ]

        if len(non_none_types) == 1:
            return non_none_types[0], True

    return field_type, False


# ============================================================
# Field Presentation
# ============================================================


def format_field_label(
    field_name: str,
) -> str:

    special_terms = {
        "ebitda": "EBITDA",
        "nfp": "NFP",
        "id": "ID",
    }

    words = field_name.split("_")

    formatted_words = []

    for word in words:

        if word.lower() in special_terms:

            formatted_words.append(
                special_terms[word.lower()]
            )

        else:

            formatted_words.append(
                word.capitalize()
            )

    return " ".join(formatted_words)


def format_field_description(
    field_name: str,
) -> str:

    descriptions = {

        "position_id": (
            "Unique identifier of the credit position."
        ),

        "revenue": (
            "Total company revenue."
        ),

        "change_in_finished_goods_inventory": (
            "Change in finished goods inventory."
        ),

        "operating_grants": (
            "Operating grants received by the company."
        ),

        "net_purchases": (
            "Net purchases of raw materials and goods."
        ),

        "change_in_raw_materials_inventory": (
            "Change in raw materials inventory."
        ),

        "costs_for_services_and_third_party_assets": (
            "Costs related to services and third-party assets."
        ),

        "personnel_costs": (
            "Personnel and employee-related costs."
        ),

        "depreciation_tangible_assets": (
            "Depreciation of tangible fixed assets."
        ),

        "working_capital_impairments": (
            "Impairments related to working capital."
        ),

        "operating_provisions": (
            "Operating provisions and related adjustments."
        ),

        "other_income_expenses_balance": (
            "Net balance of other operating income and expenses."
        ),

        "operating_value_added": (
            "Derived operating value added."
        ),

        "gross_operating_margin": (
            "Gross operating margin generated by the company."
        ),

        "net_operating_margin": (
            "Net operating margin after operating costs."
        ),

        "ebitda": (
            "Earnings before interest, taxes, "
            "depreciation and amortization."
        ),

        "profit_loss": (
            "Reported profit or loss for the company."
        ),

        "ebitda_margin": (
            "EBITDA expressed as a percentage of revenue."
        ),

        "ebitda_inventory_contribution": (
            "Contribution of inventory changes to EBITDA."
        ),

        "nfp_to_ebitda": (
            "Net financial position relative to EBITDA; "
            "a leverage indicator."
        ),

        "interest_expense": (
            "Financial expense related to interest."
        ),

        "revenue_growth": (
            "Year-over-year change in company revenue."
        ),
    }

    return descriptions.get(
        field_name,
        f"Input value for {format_field_label(field_name)}.",
    )


def format_field_value(
    field_name: str,
    value: Any,
) -> str:

    if value is None:
        return "Not available"

    if field_name == "position_id":
        return str(value)

    if field_name in {
        "revenue_growth",
        "ebitda_margin",
    }:
        return f"{float(value):.1%}"

    if field_name in {
        "revenue",
        "change_in_finished_goods_inventory",
        "operating_grants",
        "net_purchases",
        "change_in_raw_materials_inventory",
        "costs_for_services_and_third_party_assets",
        "personnel_costs",
        "depreciation_tangible_assets",
        "working_capital_impairments",
        "operating_provisions",
        "other_income_expenses_balance",
        "operating_value_added",
        "gross_operating_margin",
        "net_operating_margin",
        "ebitda",
        "profit_loss",
        "ebitda_inventory_contribution",
        "interest_expense",
    }:
        return f"€{float(value):,.0f}"

    if field_name == "nfp_to_ebitda":
        return f"{float(value):.2f}x"

    if isinstance(value, float):
        return f"{value:,.4f}"

    return str(value)


def get_field_unit(
    field_name: str,
) -> str:

    units = {

        "position_id": "Identifier",

        "revenue_growth": "%",
        "ebitda_margin": "%",

        "revenue": "EUR",
        "change_in_finished_goods_inventory": "EUR",
        "operating_grants": "EUR",
        "net_purchases": "EUR",
        "change_in_raw_materials_inventory": "EUR",
        "costs_for_services_and_third_party_assets": "EUR",
        "personnel_costs": "EUR",
        "depreciation_tangible_assets": "EUR",
        "working_capital_impairments": "EUR",
        "operating_provisions": "EUR",
        "other_income_expenses_balance": "EUR",
        "operating_value_added": "EUR",
        "gross_operating_margin": "EUR",
        "net_operating_margin": "EUR",
        "ebitda": "EUR",
        "profit_loss": "EUR",
        "ebitda_inventory_contribution": "EUR",
        "interest_expense": "EUR",

        "nfp_to_ebitda": "x",
    }

    return units.get(
        field_name,
        "",
    )


# ============================================================
# Scenario / Position Data Presentation
# ============================================================


def build_scenario_data_table(
    position: CreditPosition,
) -> list[dict[str, str]]:

    rows = []

    for field in fields(position):

        field_name = field.name

        value = getattr(
            position,
            field_name,
        )

        rows.append(
            {
                "Financial Indicator": format_field_label(
                    field_name
                ),
                "Value": format_field_value(
                    field_name,
                    value,
                ),
                "Unit": get_field_unit(
                    field_name
                ),
                "Description": format_field_description(
                    field_name
                ),
            }
        )

    return rows


def display_position_table(
    position: CreditPosition,
) -> None:

    position_data = build_scenario_data_table(
        position
    )

    st.dataframe(
        position_data,
        width="stretch",
        hide_index=True,
        column_config={
            "Financial Indicator": st.column_config.TextColumn(
                "Financial Indicator",
                width="medium",
            ),
            "Value": st.column_config.TextColumn(
                "Value",
                width="medium",
            ),
            "Unit": st.column_config.TextColumn(
                "Unit",
                width="small",
            ),
            "Description": st.column_config.TextColumn(
                "What it represents",
                width="large",
            ),
        },
    )


# ============================================================
# Manual Input
# ============================================================


def create_optional_numeric_field(
    field_name: str,
    label: str,
    resolved_type: Any,
    default: Any,
) -> Any:

    provided_key = (
        f"credit_position_{field_name}_provided"
    )

    value_key = (
        f"credit_position_{field_name}_value"
    )

    provided = st.checkbox(
        f"Provide {label}",
        value=default is not None,
        key=provided_key,
    )

    if not provided:
        return None

    if resolved_type is int:

        value = st.number_input(
            label,
            value=(
                int(default)
                if default is not None
                else 0
            ),
            step=1,
            key=value_key,
        )

        _render_field_metadata(
            description=format_field_description(
                field_name
            ),
            unit=get_field_unit(
                field_name
            ),
        )

        return value

    if resolved_type is float:

        value = st.number_input(
            label,
            value=(
                float(default)
                if default is not None
                else 0.0
            ),
            step=0.01,
            format="%.4f",
            key=value_key,
        )

        _render_field_metadata(
            description=format_field_description(
                field_name
            ),
            unit=get_field_unit(
                field_name
            ),
        )

        return value

    raise TypeError(
        f"Unsupported optional numeric type: "
        f"{field_name} -> {resolved_type}"
    )


def create_streamlit_field(
    field,
    field_type: Any,
) -> Any:

    field_name = field.name

    label = format_field_label(
        field_name
    )

    default = get_field_default(
        field
    )

    resolved_type, is_optional = (
        unwrap_optional(field_type)
    )

    description = format_field_description(
        field_name
    )

    unit = get_field_unit(
        field_name
    )

    # --------------------------------------------------------
    # String
    # --------------------------------------------------------

    if resolved_type is str and not is_optional:

        value = st.text_input(
            label,
            value=(
                ""
                if default is None
                else str(default)
            ),
            key=f"credit_position_{field_name}",
        )

        _render_field_metadata(
            description=description,
            unit=unit,
        )

        return value

    # --------------------------------------------------------
    # Optional String
    # --------------------------------------------------------

    if resolved_type is str and is_optional:

        provided = st.checkbox(
            f"Provide {label}",
            value=default is not None,
            key=(
                f"credit_position_{field_name}_provided"
            ),
        )

        if not provided:
            return None

        value = st.text_input(
            label,
            value=(
                ""
                if default is None
                else str(default)
            ),
            key=(
                f"credit_position_{field_name}_value"
            ),
        )

        _render_field_metadata(
            description=description,
            unit=unit,
        )

        return value

    # --------------------------------------------------------
    # Required Integer
    # --------------------------------------------------------

    if resolved_type is int and not is_optional:

        value = st.number_input(
            label,
            value=(
                0
                if default is None
                else int(default)
            ),
            step=1,
            key=f"credit_position_{field_name}",
        )

        _render_field_metadata(
            description=description,
            unit=unit,
        )

        return value

    # --------------------------------------------------------
    # Required Float
    # --------------------------------------------------------

    if resolved_type is float and not is_optional:

        value = st.number_input(
            label,
            value=(
                0.0
                if default is None
                else float(default)
            ),
            step=0.01,
            format="%.4f",
            key=f"credit_position_{field_name}",
        )

        _render_field_metadata(
            description=description,
            unit=unit,
        )

        return value

    # --------------------------------------------------------
    # Optional Numeric
    # --------------------------------------------------------

    if (
        is_optional
        and resolved_type in {int, float}
    ):

        return create_optional_numeric_field(
            field_name=field_name,
            label=label,
            resolved_type=resolved_type,
            default=default,
        )

    raise TypeError(
        f"Unsupported CreditPosition field type: "
        f"{field_name} -> {field_type}"
    )


# ============================================================
# Field Metadata
# ============================================================


def _render_field_metadata(
    *,
    description: str,
    unit: str,
) -> None:
    """
    Render compact metadata below an input field.
    """

    if unit:

        st.caption(
            f"{description} · Unit: {unit}"
        )

    else:

        st.caption(
            description
        )


# ============================================================
# Input Layout
# ============================================================


FIELD_GROUPS: dict[str, list[str]] = {

    "Identification": [
        "position_id",
    ],

    "Financial Performance": [
        "revenue",
        "revenue_growth",
        "ebitda",
        "ebitda_margin",
        "profit_loss",
    ],

    "Operating Data": [
        "change_in_finished_goods_inventory",
        "operating_grants",
        "net_purchases",
        "change_in_raw_materials_inventory",
        "costs_for_services_and_third_party_assets",
        "personnel_costs",
        "depreciation_tangible_assets",
        "working_capital_impairments",
        "operating_provisions",
        "other_income_expenses_balance",
        "operating_value_added",
        "gross_operating_margin",
        "net_operating_margin",
        "ebitda_inventory_contribution",
    ],

    "Leverage & Financial Structure": [
        "nfp_to_ebitda",
        "interest_expense",
    ],
}


def _build_field_lookup() -> dict[str, Any]:
    """
    Build a lookup from field name to dataclass field.

    The dataclass remains the source of truth.
    """

    return {
        field.name: field
        for field in get_credit_position_fields()
    }


def _render_field_group(
    *,
    group_title: str,
    field_names: list[str],
    field_lookup: dict[str, Any],
    type_hints: dict[str, Any],
    position_data: dict[str, Any],
) -> None:
    """
    Render one logical group of CreditPosition fields.
    """

    available_fields = [
        field_name
        for field_name in field_names
        if field_name in field_lookup
    ]

    if not available_fields:
        return

    # --------------------------------------------------------
    # Group Header
    # --------------------------------------------------------

    st.html(
        f"""
        <div class="input-group-header">
            <div class="input-group-title">
                {group_title}
            </div>
        </div>
        """
    )

    # --------------------------------------------------------
    # Identification
    # --------------------------------------------------------

    if group_title == "Identification":

        field_name = available_fields[0]

        position_data[field_name] = (
            create_streamlit_field(
                field=field_lookup[field_name],
                field_type=type_hints[field_name],
            )
        )

        return

    # --------------------------------------------------------
    # Two-column layout
    # --------------------------------------------------------

    columns = st.columns(2)

    for index, field_name in enumerate(
        available_fields
    ):

        with columns[index % 2]:

            position_data[field_name] = (
                create_streamlit_field(
                    field=field_lookup[field_name],
                    field_type=type_hints[field_name],
                )
            )


# ============================================================
# Input Introduction
# ============================================================


def _render_input_introduction() -> None:
    """
    Render the introduction card for manual CreditPosition input.

    Uses st.html() instead of st.markdown() so the HTML structure
    is rendered consistently across Streamlit environments.
    """

    st.html(
        """
        <div class="input-introduction">

            <div class="input-introduction-title">
                Credit Position Data
            </div>

            <div class="input-introduction-description">
                Enter the financial information used by the
                deterministic assessment engine. The fields below
                correspond directly to the
                <strong>CreditPosition</strong> data model.
            </div>

            <div class="input-introduction-note">
                Assessment results are calculated separately by the
                deterministic rule engine and are not entered
                manually here.
            </div>

        </div>
        """
    )


# ============================================================
# Build CreditPosition Data
# ============================================================


def build_credit_position_from_ui() -> dict[str, Any]:
    """
    Build CreditPosition data from the Streamlit UI.

    The CreditPosition dataclass remains the source of truth
    for the actual available fields.

    FIELD_GROUPS controls presentation only.
    """

    model_fields = (
        get_credit_position_fields()
    )

    type_hints = (
        get_credit_position_type_hints()
    )

    field_lookup = _build_field_lookup()

    position_data: dict[str, Any] = {}

    # --------------------------------------------------------
    # Introduction
    # --------------------------------------------------------

    _render_input_introduction()

    # --------------------------------------------------------
    # Render known logical groups
    # --------------------------------------------------------

    rendered_fields: set[str] = set()

    for group_title, field_names in FIELD_GROUPS.items():

        _render_field_group(
            group_title=group_title,
            field_names=field_names,
            field_lookup=field_lookup,
            type_hints=type_hints,
            position_data=position_data,
        )

        rendered_fields.update(
            field_name
            for field_name in field_names
            if field_name in field_lookup
        )

    # --------------------------------------------------------
    # Safety net
    # --------------------------------------------------------

    ungrouped_fields = [
        field
        for field in model_fields
        if field.name not in rendered_fields
    ]

    if ungrouped_fields:

        _render_field_group(
            group_title="Additional Data",
            field_names=[
                field.name
                for field in ungrouped_fields
            ],
            field_lookup=field_lookup,
            type_hints=type_hints,
            position_data=position_data,
        )

    return position_data