from typing import Any

import streamlit as st

from app.ui.components import show_badge


def _rule_results(result: Any) -> list[Any]:
    """Return rule results without coupling the UI to a concrete result class."""
    rules = getattr(result, "rule_results", None)
    if rules is None:
        rules = getattr(result, "rules", None)
    return list(rules or [])


def _status_value(rule: Any) -> str:
    status = getattr(rule, "status", None)
    return getattr(status, "value", str(status or ""))


def _severity_value(rule: Any) -> str:
    severity = getattr(rule, "severity", None)
    return getattr(severity, "value", str(severity or ""))


def _format_value(value: Any) -> str:
    """Format numeric values compactly while keeping text values readable."""
    if value is None:
        return "—"
    if isinstance(value, float):
        return f"{value:,.2f}"
    return str(value)


def render_report_source(
    generator_used: str | None,
    selected_reporting_mode: str,
) -> None:
    """Render the provenance of the Executive Report."""
    if generator_used == "PRIMARY":
        if selected_reporting_mode == "Gemini + Fallback":
            show_badge("AI-generated — Gemini", "ai")
            st.caption(
                "Narrative generated by Gemini from the structured deterministic assessment."
            )
            return
        if selected_reporting_mode == "Ollama + Fallback":
            show_badge("AI-generated — Local LLM", "ai")
            st.caption(
                "Narrative generated by the local LLM from the structured deterministic assessment."
            )
            return

    if generator_used == "FALLBACK":
        show_badge("Deterministic fallback", "fallback")
        st.caption(
            "The primary LLM generator was unavailable or failed; the deterministic fallback generated the report."
        )
        return

    show_badge("Deterministic — Rule Engine", "det")
    st.caption(
        "Narrative generated deterministically from the structured assessment results."
    )


def render_report_kpis(result: Any) -> None:
    """Render the compact evidence summary at the top of the report."""
    rules = _rule_results(result)
    evaluated = [r for r in rules if _status_value(r) != "NOT_EVALUABLE"]
    triggered = [r for r in rules if _status_value(r) == "TRIGGERED"]
    critical = [r for r in triggered if _severity_value(r).upper() == "CRITICAL"]
    not_evaluable = [r for r in rules if _status_value(r) == "NOT_EVALUABLE"]

    status = getattr(getattr(result, "assessment_status", None), "value", None)
    if status is None:
        status = getattr(result, "assessment_status", "Not available")

    columns = st.columns(4)
    with columns[0]:
        st.metric("Assessment", str(status).replace("_", " ").title())
    with columns[1]:
        st.metric("Rules Triggered", len(triggered))
    with columns[2]:
        st.metric("Critical Drivers", len(critical))
    with columns[3]:
        st.metric("Rules Evaluated", len(evaluated))

    if not_evaluable:
        st.caption(
            f"{len(not_evaluable)} rule(s) could not be evaluated because required information was unavailable."
        )


def render_key_risk_drivers(result: Any) -> None:
    """Render the most decision-relevant deterministic findings."""
    triggered = [r for r in _rule_results(result) if _status_value(r) == "TRIGGERED"]

    if not triggered:
        st.markdown("### Key Risk Drivers")
        st.success("No risk rules were triggered by the available financial information.")
        return

    st.markdown("### Key Risk Drivers")
    st.caption(
        "These drivers are the deterministic evidence supporting the assessment. "
        "The narrative report does not change their status or severity."
    )

    severity_rank = {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3}
    triggered.sort(key=lambda rule: severity_rank.get(_severity_value(rule).upper(), 99))

    for rule in triggered[:5]:
        rule_name = getattr(rule, "rule_name", None) or getattr(rule, "name", None) or getattr(rule, "rule_id", "Rule")
        severity = _severity_value(rule) or "UNSPECIFIED"
        category = getattr(rule, "category", None) or "Uncategorised"
        category = getattr(category, "value", str(category))
        indicator = getattr(rule, "indicator", None) or "Indicator"
        value = _format_value(getattr(rule, "value", None))
        threshold = _format_value(getattr(rule, "threshold", None))
        reason = getattr(rule, "reason", None)

        with st.container(border=True):
            header = st.columns([4, 1, 2])
            with header[0]:
                st.markdown(f"**{rule_name}**")
            with header[1]:
                st.write(severity)
            with header[2]:
                st.write(str(category))

            evidence = st.columns(3)
            with evidence[0]:
                st.caption("Indicator")
                st.write(str(indicator))
            with evidence[1]:
                st.caption("Actual")
                st.write(value)
            with evidence[2]:
                st.caption("Threshold")
                st.write(threshold)

            if reason:
                st.caption(str(reason))

    if len(triggered) > 5:
        st.caption(f"Showing the 5 highest-priority drivers out of {len(triggered)} triggered rules.")


def render_report_findings(result: Any) -> None:
    """Render the structured findings that accompany the executive conclusion."""
    findings = getattr(getattr(result, "report", None), "findings_by_category", None) or []
    if not findings:
        return

    st.markdown("### Detailed Findings")
    for group in findings:
        category = getattr(group, "category", "Findings")
        category = getattr(category, "value", str(category))
        with st.expander(str(category).title(), expanded=False):
            for finding in getattr(group, "findings", []) or []:
                rule_id = getattr(finding, "rule_id", "Rule")
                severity = getattr(getattr(finding, "severity", None), "value", "")
                label = f"{rule_id} · {severity}" if severity else str(rule_id)
                st.markdown(f"**{label}**")
                st.write(getattr(finding, "text", str(finding)))


def render_report_limitations(result: Any) -> None:
    """Render limitations and missing-information warnings."""
    limitations = getattr(getattr(result, "report", None), "limitations", None) or []
    if not limitations:
        return

    st.markdown("### Data Limitations")
    for limitation in limitations:
        limitation_text = getattr(limitation, "text", str(limitation))
        st.write(f"• {limitation_text}")


def render_execution_metadata(result: Any) -> None:
    """Render workflow execution metadata for traceability."""
    metadata = getattr(result, "execution_metadata", None)
    if metadata is None:
        return

    with st.expander("Report Provenance & Execution Metadata", expanded=False):
        st.caption("Technical traceability for this assessment and report generation.")

        first_row = st.columns(4)
        with first_row[0]:
            st.markdown("**Execution ID**")
            st.code(metadata.execution_id, language=None)
        with first_row[1]:
            st.markdown("**Started At**")
            st.write(metadata.started_at.isoformat())
        with first_row[2]:
            st.markdown("**Reporting Mode**")
            st.write(metadata.reporting_mode)
        with first_row[3]:
            st.markdown("**Generator**")
            st.write(metadata.generator_used or "Not available")

        second_row = st.columns(4)
        with second_row[0]:
            st.markdown("**Fallback Used**")
            st.write("Yes" if metadata.fallback_used else "No")
        with second_row[1]:
            st.markdown("**Error Category**")
            st.write(metadata.error_category or "None")
        with second_row[2]:
            st.markdown("**Assessment Time**")
            st.write(f"{metadata.assessment_elapsed_time:.3f} s")
        with second_row[3]:
            st.markdown("**Analysis Time**")
            st.write(f"{metadata.analysis_elapsed_time:.3f} s")

        third_row = st.columns(2)
        with third_row[0]:
            st.markdown("**Reporting Time**")
            st.write(f"{metadata.reporting_elapsed_time:.3f} s")
        with third_row[1]:
            st.markdown("**Total Execution Time**")
            st.write(f"{metadata.total_elapsed_time:.3f} s")


def render_report_tab(
    result: Any,
    selected_reporting_mode: str,
    report_badge_kind: str,
    report_badge_label: str,
    configured_model: str | None,
) -> None:
    """Render the Executive Report as the final user-facing output."""
    generator_used = getattr(result, "report_generator_used", None)
    generation_error = getattr(result, "report_generation_error", None)

    st.markdown("# Executive Credit Assessment Report")
    st.caption(
        "Final user-facing output of the Credit Assessment System. "
        "The decision is determined by the Rule Engine; the selected reporting layer only produces the narrative."
    )

    with st.container(border=True):
        header = st.columns([3, 2])
        with header[0]:
            st.markdown("### Final Assessment")
            status = getattr(getattr(result, "assessment_status", None), "value", None)
            status = status or getattr(result, "assessment_status", "Not available")
            st.markdown(f"## {str(status).replace('_', ' ').title()}")
        with header[1]:
            st.markdown("### Report Generated By")
            show_badge(report_badge_label, report_badge_kind)
            if configured_model:
                st.caption(f"Configured model: {configured_model}")
            else:
                st.caption(f"Reporting mode: {selected_reporting_mode}")

        render_report_kpis(result)

    st.markdown("## Executive Conclusion")
    with st.container(border=True):
        st.markdown(result.report.executive_summary)

    render_key_risk_drivers(result)
    render_report_findings(result)
    render_report_limitations(result)

    if generator_used == "FALLBACK" and generation_error:
        with st.expander("Technical information", expanded=False):
            st.caption(f"Primary generator error: {generation_error}")

    render_execution_metadata(result)
