from typing import Any

import streamlit as st

from app.ui.components import show_badge


def _section_header(title: str, description: str) -> None:
    """Render a consistent visual section header."""
    st.markdown(
        f"""
        <div class="ui-section-header">
            <div class="ui-section-title">{title}</div>
            <div class="ui-section-description">{description}</div>
        </div>
        """,
        unsafe_allow_html=True,
    )


def _render_assessment_status(status: str) -> None:
    """Render the deterministic assessment status."""
    normalized = status.upper().replace(" ", "_")
    palette = {
        "CRITICAL": ("#b91c1c", "rgba(185, 28, 28, 0.10)"),
        "ATTENTION": ("#b45309", "rgba(180, 83, 9, 0.10)"),
        "NORMAL": ("#166534", "rgba(22, 101, 52, 0.10)"),
    }
    foreground, background = palette.get(
        normalized,
        ("#4b5563", "rgba(107, 114, 128, 0.10)"),
    )
    label = normalized.replace("_", " ").title()

    st.markdown(
        f"""
        <span style="
            display:inline-flex;
            align-items:center;
            padding:0.24rem 0.72rem;
            border-radius:999px;
            border:1px solid {foreground}55;
            background:{background};
            color:{foreground};
            font-size:0.78rem;
            font-weight:750;
            letter-spacing:0.02em;
        ">{label}</span>
        """,
        unsafe_allow_html=True,
    )


def render_report_source(
    generator_used: str | None,
    selected_reporting_mode: str,
    configured_model: str | None = None,
) -> None:
    """Show the actual generator used for the Executive Report."""
    if generator_used == "FALLBACK":
        show_badge("Deterministic fallback", "fallback")
        st.caption("The selected LLM was unavailable or failed.")
        return

    if generator_used == "PRIMARY" and selected_reporting_mode == "Gemini + Fallback":
        label = "AI-generated — Gemini"
        if configured_model:
            label = f"{label} · {configured_model}"
        show_badge(label, "ai")
        return

    if generator_used == "PRIMARY" and selected_reporting_mode == "Ollama + Fallback":
        label = "AI-generated — Local LLM"
        if configured_model:
            label = f"{label} · {configured_model}"
        show_badge(label, "ai")
        return

    show_badge("Deterministic — Rule Engine", "det")


def render_report_limitations(result: Any) -> None:
    """Render limitations returned by the Reporting layer."""
    limitations = getattr(getattr(result, "report", None), "limitations", None) or []
    if not limitations:
        return

    _section_header(
        "Data Limitations",
        "Information gaps that may affect the completeness of the assessment.",
    )
    for limitation in limitations:
        st.write(f"• {getattr(limitation, 'text', str(limitation))}")


def render_execution_metadata(result: Any) -> None:
    """Keep technical provenance available without occupying the main report."""
    metadata = getattr(result, "execution_metadata", None)
    if metadata is None:
        return

    with st.expander("Technical details", expanded=False):
        cols = st.columns(4)
        values = [
            ("Execution ID", getattr(metadata, "execution_id", "—")),
            ("Generator", getattr(metadata, "generator_used", "—") or "—"),
            ("Fallback", "Yes" if getattr(metadata, "fallback_used", False) else "No"),
            ("Total time", f"{getattr(metadata, 'total_elapsed_time', 0.0):.3f} s"),
        ]
        for column, (label, value) in zip(cols, values):
            with column:
                st.caption(label)
                st.write(value)


def render_report_tab(
    result: Any,
    selected_reporting_mode: str,
    report_badge_kind: str,
    report_badge_label: str,
    configured_model: str | None,
) -> None:
    """Render only the executive narrative; detailed evidence lives in dedicated UI sections."""
    report = getattr(result, "report", None)
    if report is None:
        st.error("The Executive Report is not available for this assessment.")
        return

    generator_used = getattr(result, "report_generator_used", None)
    generation_error = getattr(result, "report_generation_error", None)

    _section_header(
        "Executive Credit Assessment",
        "Final credit judgement and management summary.",
    )

    with st.container(border=True):
        header = st.columns([2, 2, 2])
        status_obj = getattr(report, "assessment_status", None)
        status = str(getattr(status_obj, "value", status_obj or "Not available"))

        with header[0]:
            st.caption("Final assessment")
            _render_assessment_status(status)
        with header[1]:
            st.caption("Report generated by")
            render_report_source(
                generator_used=generator_used,
                selected_reporting_mode=selected_reporting_mode,
                configured_model=configured_model,
            )
        with header[2]:
            st.caption("Position")
            st.write(str(getattr(report, "position_id", "Not available")))

    _section_header(
        "Executive Conclusion",
        "Management-level interpretation of the assessment and its main implications.",
    )
    with st.container(border=True):
        st.markdown(
            str(getattr(report, "executive_summary", "No executive summary available."))
        )

    render_report_limitations(result)

    if generator_used == "FALLBACK" and generation_error:
        with st.expander("Why fallback was used", expanded=False):
            st.caption(str(generation_error))

    render_execution_metadata(result)
