import streamlit as st

from app.config import (
    get_gemini_api_key,
    get_reporting_modes,
    is_streamlit_cloud,
)

from app.ui.components import show_badge


# ============================================================
# Sidebar Configuration
# ============================================================

def render_sidebar() -> str:
    """
    Render the application sidebar.

    Returns:
        The reporting mode selected by the user.
    """

    is_cloud = is_streamlit_cloud()
    reporting_modes = get_reporting_modes()

    with st.sidebar:

        st.title(
            "System Configuration"
        )

        st.caption(
            "Configure the reporting layer used by "
            "the assessment workflow."
        )

        # ----------------------------------------------------
        # Reporting Mode
        # ----------------------------------------------------

        reporting_mode = st.radio(
            "Reporting Mode",
            options=reporting_modes,
            index=0,
        )

        st.divider()

        # ----------------------------------------------------
        # Provenance Legend
        # ----------------------------------------------------

        st.subheader(
            "How to read this app"
        )

        st.markdown(
            """
            <div class="pipeline-legend">
                <div class="pipeline-legend-item">
                    <span class="legend-dot det"></span>
                    Deterministic — rule engine, fully traceable
                </div>
                <div class="pipeline-legend-item">
                    <span class="legend-dot ai"></span>
                    AI-assisted — language generated by an LLM
                </div>
            </div>
            """,
            unsafe_allow_html=True,
        )

        st.caption(
            "Every section of the app carries one of these badges "
            "so you always know whether content is guaranteed "
            "reproducible or was phrased by a language model."
        )

        st.divider()

        # ----------------------------------------------------
        # Environment Information
        # ----------------------------------------------------

        st.subheader(
            "Execution Environment"
        )

        if is_cloud:

            st.info(
                "☁️ Streamlit Community Cloud"
            )

            st.caption(
                "Ollama is not available in the cloud because "
                "the application runs inside a remote container. "
                "Deterministic reporting and Gemini are available."
            )

        else:

            st.success(
                "💻 Local Environment"
            )

            st.caption(
                "Ollama is available as a local reporting option."
            )

        st.divider()

        # ----------------------------------------------------
        # Architecture Guarantees
        # ----------------------------------------------------

        st.subheader(
            "Architecture Guarantees"
        )

        guarantee_items = [
            (
                "⚖️",
                "Deterministic decision layer",
                "The rule engine is the sole authority for status, "
                "severity and findings.",
            ),
            (
                "🧭",
                "Controlled AI usage",
                "The LLM only rewrites findings into prose — it never "
                "decides the outcome.",
            ),
            (
                "🔗",
                "Traceability",
                "Every report finding links back to a specific "
                "deterministic rule.",
            ),
            (
                "🛟",
                "Automatic fallback",
                "If the LLM is unavailable during report generation, "
                "the deterministic report generator takes over.",
            ),
        ]

        for icon, title, description in guarantee_items:

            st.markdown(
                f"**{icon} {title}**  \n"
                f"<span style='color:var(--muted); font-size:0.82rem;'>"
                f"{description}</span>",
                unsafe_allow_html=True,
            )

        st.divider()

        # ----------------------------------------------------
        # Selected Reporting Mode
        # ----------------------------------------------------

        st.subheader(
            "Selected Reporting Mode"
        )

        if reporting_mode == "Gemini + Fallback":

            gemini_key = get_gemini_api_key()

            show_badge(
                "AI-assisted (Gemini)",
                "ai",
            )

            if gemini_key:

                st.success(
                    "Gemini reporting enabled"
                )

                st.caption(
                    "Gemini is used exclusively for executive "
                    "report generation."
                )

            else:

                st.warning(
                    "Gemini selected, but GEMINI_API_KEY "
                    "is not configured."
                )

                st.caption(
                    "Configure the Gemini API key before "
                    "running the assessment."
                )

        elif reporting_mode == "Ollama + Fallback":

            show_badge(
                "AI-assisted (Local LLM)",
                "ai",
            )

            st.success(
                "Local LLM reporting enabled"
            )

            st.caption(
                "A local language model is used exclusively "
                "for executive report generation."
            )

        else:

            show_badge(
                "Fully deterministic",
                "det",
            )

            st.info(
                "Deterministic reporting enabled"
            )

            st.caption(
                "No external LLM call is required. The executive "
                "report is generated deterministically."
            )

    return reporting_mode