import streamlit as st

# ============================================================
# Styling
# ============================================================
#
# Design language:
#
#   Deterministic
#       Blue accent. Used for rule-engine outputs and all
#       reproducible / traceable assessment information.
#
#   AI-assisted
#       Violet accent. Used for content generated by an LLM.
#
#   Fallback
#       Amber accent. Used when an LLM was requested but the
#       deterministic fallback generator was used.
#
# Responsive behaviour:
#
#   Desktop / Tablet
#       Data is displayed using the standard Streamlit dataframe.
#
#   Mobile
#       Financial indicators are displayed as vertical cards.
#
# ============================================================


def apply_styles() -> None:
    st.markdown(
        """
        <style>

        /* ==================================================== */
        /* Design Tokens                                        */
        /* ==================================================== */

        :root {

            --det-color: #2563eb;
            --det-bg: rgba(37, 99, 235, 0.08);

            --ai-color: #7c3aed;
            --ai-bg: rgba(124, 58, 237, 0.08);

            --fallback-color: #b45309;
            --fallback-bg: rgba(180, 83, 9, 0.10);

            --muted: #6b7280;
            --border: rgba(128, 128, 128, 0.20);

            --card-bg: rgba(128, 128, 128, 0.025);

            --radius: 0.75rem;
            --input-radius: 0.55rem;
        }


        /* ==================================================== */
        /* Global Layout / Overflow                             */
        /* ==================================================== */

        html,
        body {
            max-width: 100%;
            overflow-x: hidden;
        }

        #root {
            max-width: 100%;
            overflow-x: hidden;
        }

        *,
        *::before,
        *::after {
            box-sizing: border-box;
        }

        .block-container {
            width: 100%;
            max-width: 1400px;

            padding-top: 1.6rem;
            padding-bottom: 3rem;

            padding-left: clamp(1rem, 3vw, 3rem);
            padding-right: clamp(1rem, 3vw, 3rem);

            box-sizing: border-box;
        }


        /* ==================================================== */
        /* Typography                                           */
        /* ==================================================== */

        h1,
        h2,
        h3 {
            letter-spacing: -0.01em;
        }

        .app-subtitle {
            color: var(--muted);

            font-size: 1rem;
            line-height: 1.5;

            margin-top: -0.4rem;
            margin-bottom: 1.2rem;
        }


        /* ==================================================== */
        /* Provenance Badges                                    */
        /* ==================================================== */

        .badge {
            display: inline-flex;
            align-items: center;

            gap: 0.35rem;

            max-width: 100%;

            padding: 0.22rem 0.65rem;

            border-radius: 999px;

            font-size: 0.75rem;
            font-weight: 650;

            letter-spacing: 0.01em;

            border: 1px solid transparent;

            white-space: normal;
            overflow-wrap: anywhere;
            word-break: break-word;
        }

        .badge-det {
            color: var(--det-color);
            background: var(--det-bg);
            border-color: rgba(37, 99, 235, 0.25);
        }

        .badge-ai {
            color: var(--ai-color);
            background: var(--ai-bg);
            border-color: rgba(124, 58, 237, 0.25);
        }

        .badge-fallback {
            color: var(--fallback-color);
            background: var(--fallback-bg);
            border-color: rgba(180, 83, 9, 0.28);
        }

        .badge-row {
            margin-bottom: 0.6rem;
        }


        /* ==================================================== */
        /* Pipeline / Workflow                                  */
        /* ==================================================== */

        .pipeline-wrap {
            display: flex;
            align-items: stretch;

            gap: 0.4rem;

            margin: 0.4rem 0 0.8rem 0;

            width: 100%;
            max-width: 100%;
        }

        .pipeline-step {
            flex: 1;
            min-width: 0;

            padding: 1rem 0.9rem;

            border-radius: var(--radius);

            border: 1.5px solid var(--border);

            background: var(--card-bg);

            min-height: 108px;

            position: relative;

            overflow-wrap: anywhere;
            word-break: break-word;
        }

        .pipeline-step.det {
            border-color: rgba(37, 99, 235, 0.35);
            background: var(--det-bg);
        }

        .pipeline-step.ai {
            border-color: rgba(124, 58, 237, 0.35);
            background: var(--ai-bg);
        }

        .pipeline-arrow {
            display: flex;
            align-items: center;
            justify-content: center;

            color: var(--muted);

            font-size: 1.1rem;

            padding: 0 0.1rem;

            flex-shrink: 0;
        }

        .pipeline-number {
            font-size: 0.72rem;

            font-weight: 750;

            color: var(--muted);

            letter-spacing: 0.06em;
        }

        .pipeline-title {
            font-weight: 650;

            margin-top: 0.25rem;

            font-size: 0.92rem;
        }

        .pipeline-description {
            color: var(--muted);

            font-size: 0.76rem;

            margin-top: 0.1rem;

            line-height: 1.35;
        }


        /* ==================================================== */
        /* Pipeline Legend                                      */
        /* ==================================================== */

        .pipeline-legend {
            display: flex;

            gap: 1.4rem;

            margin-top: 0.4rem;
            margin-bottom: 0.2rem;

            flex-wrap: wrap;
        }

        .pipeline-legend-item {
            display: flex;
            align-items: center;

            gap: 0.4rem;

            font-size: 0.78rem;

            color: var(--muted);

            min-width: 0;

            overflow-wrap: anywhere;
            word-break: break-word;
        }

        .legend-dot {
            width: 0.65rem;
            height: 0.65rem;

            min-width: 0.65rem;

            border-radius: 50%;

            display: inline-block;
        }

        .legend-dot.det {
            background: var(--det-color);
        }

        .legend-dot.ai {
            background: var(--ai-color);
        }


        /* ==================================================== */
        /* Generic Cards                                        */
        /* ==================================================== */

        .scenario-card {
            width: 100%;
            max-width: 100%;

            padding: 1.2rem 1.4rem;

            border-radius: var(--radius);

            border: 1px solid var(--border);

            background: var(--card-bg);

            margin-bottom: 1rem;

            overflow-wrap: anywhere;
            word-break: break-word;
        }

        .scenario-title {
            font-size: 1.1rem;

            font-weight: 650;

            margin-bottom: 0.4rem;
        }

        .scenario-description {
            color: var(--muted);

            font-size: 0.88rem;

            line-height: 1.5;
        }

        .data-introduction {
            color: var(--muted);

            font-size: 0.88rem;

            line-height: 1.5;

            margin-bottom: 1rem;
        }

        .data-note {
            width: 100%;
            max-width: 100%;

            padding: 0.9rem 1rem;

            border-radius: 0.6rem;

            border: 1px solid var(--border);

            background: var(--card-bg);

            margin-bottom: 1rem;

            font-size: 0.85rem;

            color: var(--muted);

            overflow-wrap: anywhere;
            word-break: break-word;
        }


        /* ==================================================== */
        /* Manual Input Introduction                            */
        /* ==================================================== */

        .input-introduction {
            width: 100%;
            max-width: 100%;

            padding: 1rem 1.15rem;

            margin: 0.5rem 0 1.2rem 0;

            border-radius: var(--radius);

            border: 1px solid var(--border);

            background: var(--card-bg);

            overflow-wrap: anywhere;
            word-break: break-word;
        }

        .input-introduction-title {
            font-size: 1rem;

            font-weight: 700;

            line-height: 1.35;

            margin-bottom: 0.35rem;
        }

        .input-introduction-description {
            color: var(--muted);

            font-size: 0.86rem;

            line-height: 1.5;
        }

        .input-introduction-description strong {
            color: inherit;

            font-weight: 650;
        }

        .input-introduction-note {
            margin-top: 0.75rem;

            padding-top: 0.7rem;

            border-top: 1px dashed var(--border);

            color: var(--muted);

            font-size: 0.78rem;

            line-height: 1.45;
        }


        /* ==================================================== */
        /* Manual Input Groups                                  */
        /* ==================================================== */

        .input-group-header {
            width: 100%;
            max-width: 100%;

            margin-top: 1.4rem;
            margin-bottom: 0.7rem;

            padding-bottom: 0.45rem;

            border-bottom: 1px solid var(--border);
        }

        .input-group-title {
            font-size: 0.95rem;

            font-weight: 700;

            line-height: 1.35;

            color: inherit;
        }

        .input-group-header::before {
            content: "";

            display: inline-block;

            width: 0.3rem;
            height: 0.95rem;

            margin-right: 0.5rem;

            vertical-align: -0.12rem;

            border-radius: 999px;

            background: var(--det-color);
        }


        /* ==================================================== */
        /* Streamlit Input Fields                               */
        /* ==================================================== */

        [data-testid="stTextInput"],
        [data-testid="stNumberInput"] {
            width: 100%;
            max-width: 100%;
        }

        [data-testid="stTextInput"] input,
        [data-testid="stNumberInput"] input {
            width: 100%;
            max-width: 100%;

            box-sizing: border-box;

            border-radius: var(--input-radius);
        }

        [data-testid="stTextInput"] label,
        [data-testid="stNumberInput"] label {
            font-weight: 600;
        }

        [data-testid="stTextInput"] small,
        [data-testid="stNumberInput"] small {
            color: var(--muted);
        }

        [data-testid="stTextInput"] *,
        [data-testid="stNumberInput"] * {
            max-width: 100%;
            box-sizing: border-box;
        }


        /* ==================================================== */
        /* Checkbox / Optional Fields                           */
        /* ==================================================== */

        [data-testid="stCheckbox"] {
            margin-top: 0.15rem;
            margin-bottom: 0.15rem;
        }

        [data-testid="stCheckbox"] label {
            font-size: 0.84rem;

            font-weight: 550;
        }


        /* ==================================================== */
        /* Selectbox / Radio                                    */
        /* ==================================================== */

        [data-testid="stSelectbox"],
        [data-testid="stRadio"] {
            width: 100%;
            max-width: 100%;
        }

        [data-testid="stRadio"] label {
            min-width: 0;

            overflow-wrap: anywhere;
            word-break: break-word;
        }


        /* ==================================================== */
        /* Field Metadata                                       */
        /* ==================================================== */

        [data-testid="stTextInput"] + *,
        [data-testid="stNumberInput"] + * {
            max-width: 100%;
        }


        /* ==================================================== */
        /* Provenance Panel                                     */
        /* ==================================================== */

        .provenance-panel {
            width: 100%;
            max-width: 100%;

            border-radius: var(--radius);

            border: 1px solid var(--border);

            padding: 1.1rem 1.3rem;

            margin-bottom: 1.2rem;

            background: rgba(128, 128, 128, 0.02);

            overflow-wrap: anywhere;
            word-break: break-word;
        }

        .provenance-row {
            display: flex;
            align-items: center;
            justify-content: space-between;

            gap: 1rem;

            padding: 0.45rem 0;

            border-bottom: 1px dashed var(--border);

            font-size: 0.87rem;

            overflow-wrap: anywhere;
            word-break: break-word;
        }

        .provenance-row:last-child {
            border-bottom: none;
        }

        .provenance-label {
            color: inherit;

            font-weight: 550;
        }

        .metric-description {
            color: var(--muted);

            font-size: 0.78rem;

            line-height: 1.45;
        }


        /* ==================================================== */
        /* Section Cards                                        */
        /* ==================================================== */

        .section-card {
            width: 100%;
            max-width: 100%;

            border-radius: var(--radius);

            border: 1.5px solid var(--border);

            padding: 1rem 1.2rem;

            margin-bottom: 1rem;

            overflow-wrap: anywhere;
            word-break: break-word;
        }

        .section-card.det {
            border-left: 4px solid var(--det-color);
        }

        .section-card.ai {
            border-left: 4px solid var(--ai-color);
        }

        .section-card.fallback {
            border-left: 4px solid var(--fallback-color);
        }


        /* ==================================================== */
        /* Deterministic Finding Cards                          */
        /* ==================================================== */

        .finding-card {
            width: 100%;
            max-width: 100%;

            padding: 1rem 1.15rem;

            margin-bottom: 0.8rem;

            border-radius: var(--radius);

            border: 1px solid var(--border);

            background: var(--card-bg);

            overflow: hidden;

            transition:
                border-color 0.15s ease,
                transform 0.15s ease;
        }

        .finding-card:hover {
            border-color: rgba(37, 99, 235, 0.35);

            transform: translateY(-1px);
        }

        .finding-header {
            display: flex;

            align-items: center;
            justify-content: space-between;

            gap: 0.75rem;

            margin-bottom: 0.55rem;

            width: 100%;
            max-width: 100%;
        }

        .finding-rule {
            font-size: 0.82rem;

            font-weight: 750;

            letter-spacing: 0.04em;

            color: var(--det-color);

            min-width: 0;
            max-width: 100%;

            overflow-wrap: anywhere;
            word-break: break-word;
        }

        .finding-severity {
            flex-shrink: 0;

            padding: 0.18rem 0.55rem;

            border-radius: 999px;

            font-size: 0.70rem;

            font-weight: 700;

            text-transform: uppercase;

            letter-spacing: 0.04em;

            color: var(--det-color);

            background: var(--det-bg);

            border: 1px solid rgba(37, 99, 235, 0.25);
        }

        .finding-severity.high,
        .finding-severity.critical {
            color: var(--fallback-color);

            background: var(--fallback-bg);

            border-color: rgba(180, 83, 9, 0.28);
        }

        .finding-category {
            font-size: 0.78rem;

            font-weight: 700;

            letter-spacing: 0.04em;

            margin-bottom: 0.4rem;

            color: inherit;

            overflow-wrap: anywhere;
            word-break: break-word;
        }

        .finding-description {
            color: var(--muted);

            font-size: 0.86rem;

            line-height: 1.5;

            overflow-wrap: anywhere;
            word-break: break-word;
        }


        /* ==================================================== */
        /* Guarantee Items                                      */
        /* ==================================================== */

        .guarantee-item {
            width: 100%;
            max-width: 100%;

            padding: 0.55rem 0;

            border-bottom: 1px dashed var(--border);

            overflow-wrap: anywhere;
            word-break: break-word;
        }

        .guarantee-item:last-child {
            border-bottom: none;
        }

        .guarantee-title {
            font-weight: 600;

            font-size: 0.86rem;

            line-height: 1.35;

            overflow-wrap: anywhere;
            word-break: break-word;
        }

        .guarantee-description {
            display: block;

            margin-top: 0.2rem;

            line-height: 1.4;

            overflow-wrap: anywhere;
            word-break: break-word;
        }


        /* ==================================================== */
        /* Position Data Table - Desktop / Tablet              */
        /* ==================================================== */

        /*
         * Desktop and tablet use the standard Streamlit
         * dataframe.
         *
         * The wrapper provides horizontal overflow protection.
         */

        .responsive-table-desktop {
            display: block;

            width: 100%;
            max-width: 100%;

            overflow-x: auto;
            overflow-y: hidden;

            -webkit-overflow-scrolling: touch;

            border-radius: var(--radius);

            margin-bottom: 1rem;
        }


        /* ==================================================== */
        /* Position Data Cards - Mobile                        */
        /* ==================================================== */

        /*
         * Hidden by default.
         *
         * The responsive_table.py renderer always creates both
         * representations. CSS determines which one is visible.
         */

        .responsive-table-mobile {
            display: none;

            width: 100%;
            max-width: 100%;

            margin-top: 0.25rem;
        }


        /* ---------------------------------------------------- */
        /* Individual financial indicator card                 */
        /* ---------------------------------------------------- */

        .position-data-card {
            width: 100%;
            max-width: 100%;

            padding: 0.95rem 1rem;

            margin-bottom: 0.7rem;

            border-radius: var(--radius);

            border: 1px solid var(--border);

            background: var(--card-bg);

            overflow: hidden;

            overflow-wrap: anywhere;
            word-break: break-word;
        }


        /* ---------------------------------------------------- */
        /* Indicator name                                       */
        /* ---------------------------------------------------- */

        .position-data-card-header {
            width: 100%;
            max-width: 100%;

            font-size: 0.80rem;

            font-weight: 700;

            line-height: 1.35;

            color: var(--muted);

            margin-bottom: 0.45rem;

            overflow-wrap: anywhere;
            word-break: break-word;
        }


        /* ---------------------------------------------------- */
        /* Indicator value                                      */
        /* ---------------------------------------------------- */

        .position-data-card-value {
            width: 100%;
            max-width: 100%;

            font-size: 1.15rem;

            font-weight: 750;

            line-height: 1.25;

            color: inherit;

            overflow-wrap: anywhere;
            word-break: break-word;
        }


        /* ---------------------------------------------------- */
        /* Indicator unit                                       */
        /* ---------------------------------------------------- */

        .position-data-card-unit {
            width: 100%;
            max-width: 100%;

            margin-top: 0.15rem;

            font-size: 0.70rem;

            font-weight: 600;

            color: var(--det-color);

            letter-spacing: 0.03em;

            text-transform: uppercase;

            overflow-wrap: anywhere;
            word-break: break-word;
        }


        /* ---------------------------------------------------- */
        /* Indicator description                               */
        /* ---------------------------------------------------- */

        .position-data-card-description {
            width: 100%;
            max-width: 100%;

            margin-top: 0.65rem;

            padding-top: 0.6rem;

            border-top: 1px dashed var(--border);

            color: var(--muted);

            font-size: 0.76rem;

            line-height: 1.45;

            overflow-wrap: anywhere;
            word-break: break-word;
        }


        /* ==================================================== */
        /* Footer                                               */
        /* ==================================================== */

        .footer {
            margin-top: 2rem;

            padding-top: 1rem;

            border-top: 1px solid var(--border);

            color: var(--muted);

            font-size: 0.78rem;

            line-height: 1.5;

            overflow-wrap: anywhere;
            word-break: break-word;
        }


        /* ==================================================== */
        /* Tablet                                               */
        /* ==================================================== */

        @media (max-width: 900px) {

            .block-container {
                padding-top: 1.2rem;
                padding-bottom: 2rem;

                padding-left: 1rem;
                padding-right: 1rem;
            }

            .pipeline-wrap {
                flex-wrap: wrap;
            }

            .pipeline-step {
                flex: 1 1 calc(50% - 0.4rem);

                min-width: 220px;
            }

            .pipeline-arrow {
                display: none;
            }

            .section-card {
                padding: 0.9rem 1rem;
            }

            .scenario-card {
                padding: 1rem;
            }

            .input-introduction {
                padding: 0.95rem 1rem;
            }

            .responsive-table-desktop {
                overflow-x: auto;
            }
        }


        /* ==================================================== */
        /* Mobile                                               */
        /* ==================================================== */

        @media (max-width: 640px) {

            /* ----------------------------------------------- */
            /* Main container                                  */
            /* ----------------------------------------------- */

            .block-container {
                padding-top: 0.8rem;
                padding-bottom: 1.5rem;

                padding-left: 0.75rem;
                padding-right: 0.75rem;
            }


            /* ----------------------------------------------- */
            /* Typography                                      */
            /* ----------------------------------------------- */

            .app-subtitle {
                font-size: 0.88rem;

                margin-top: -0.2rem;

                margin-bottom: 1rem;
            }


            /* ----------------------------------------------- */
            /* Badges                                          */
            /* ----------------------------------------------- */

            .badge {
                font-size: 0.70rem;

                padding: 0.20rem 0.55rem;

                line-height: 1.35;

                white-space: normal;

                overflow-wrap: anywhere;
                word-break: break-word;
            }


            /* ----------------------------------------------- */
            /* Pipeline                                        */
            /* ----------------------------------------------- */

            .pipeline-wrap {
                display: flex;

                flex-direction: column;

                gap: 0.6rem;
            }

            .pipeline-step {
                flex: none;

                width: 100%;

                min-width: 0;
                min-height: auto;

                padding: 0.85rem;
            }

            .pipeline-arrow {
                display: none;
            }

            .pipeline-title {
                font-size: 0.88rem;
            }

            .pipeline-description {
                font-size: 0.75rem;
            }


            /* ----------------------------------------------- */
            /* Legend                                          */
            /* ----------------------------------------------- */

            .pipeline-legend {
                flex-direction: column;

                gap: 0.5rem;
            }

            .pipeline-legend-item {
                font-size: 0.75rem;
            }


            /* ----------------------------------------------- */
            /* Generic cards                                   */
            /* ----------------------------------------------- */

            .scenario-card {
                padding: 0.9rem;

                border-radius: 0.65rem;
            }

            .scenario-title {
                font-size: 1rem;
            }

            .scenario-description,
            .data-introduction {
                font-size: 0.84rem;
            }

            .data-note {
                padding: 0.8rem;

                font-size: 0.80rem;
            }


            /* ----------------------------------------------- */
            /* Manual Input Introduction                       */
            /* ----------------------------------------------- */

            .input-introduction {
                padding: 0.85rem;

                margin-top: 0.35rem;
                margin-bottom: 1rem;

                border-radius: 0.65rem;
            }

            .input-introduction-title {
                font-size: 0.92rem;
            }

            .input-introduction-description {
                font-size: 0.80rem;

                line-height: 1.45;
            }

            .input-introduction-note {
                margin-top: 0.65rem;

                padding-top: 0.6rem;

                font-size: 0.74rem;

                line-height: 1.4;
            }


            /* ----------------------------------------------- */
            /* Input Groups                                    */
            /* ----------------------------------------------- */

            .input-group-header {
                margin-top: 1.15rem;

                margin-bottom: 0.6rem;

                padding-bottom: 0.4rem;
            }

            .input-group-title {
                font-size: 0.86rem;

                line-height: 1.3;
            }

            .input-group-header::before {
                width: 0.25rem;
                height: 0.85rem;

                margin-right: 0.4rem;
            }


            /* ----------------------------------------------- */
            /* Streamlit Inputs                                */
            /* ----------------------------------------------- */

            [data-testid="stTextInput"],
            [data-testid="stNumberInput"],
            [data-testid="stSelectbox"] {
                width: 100%;
                max-width: 100%;
            }

            [data-testid="stTextInput"] input,
            [data-testid="stNumberInput"] input {
                min-height: 2.55rem;

                font-size: 0.92rem;
            }

            [data-testid="stTextInput"] label,
            [data-testid="stNumberInput"] label {
                font-size: 0.82rem;
            }

            [data-testid="stCheckbox"] {
                margin-top: 0.1rem;
            }

            [data-testid="stCheckbox"] label {
                font-size: 0.78rem;
            }


            /* ----------------------------------------------- */
            /* Columns                                         */
            /* ----------------------------------------------- */

            [data-testid="stHorizontalBlock"] {
                gap: 0.65rem;
            }


            /* ----------------------------------------------- */
            /* Provenance                                      */
            /* ----------------------------------------------- */

            .provenance-panel {
                padding: 0.9rem;
            }

            .provenance-row {
                flex-direction: column;

                align-items: flex-start;

                gap: 0.35rem;
            }


            /* ----------------------------------------------- */
            /* Section Cards                                   */
            /* ----------------------------------------------- */

            .section-card {
                padding: 0.85rem 0.9rem;

                margin-bottom: 0.75rem;
            }


            /* ----------------------------------------------- */
            /* Finding Cards                                   */
            /* ----------------------------------------------- */

            .finding-card {
                padding: 0.85rem;

                border-radius: 0.65rem;

                margin-bottom: 0.65rem;
            }

            .finding-header {
                align-items: flex-start;

                gap: 0.5rem;

                margin-bottom: 0.5rem;
            }

            .finding-rule {
                font-size: 0.78rem;
            }

            .finding-severity {
                font-size: 0.64rem;

                padding: 0.16rem 0.45rem;
            }

            .finding-category {
                font-size: 0.72rem;
            }

            .finding-description {
                font-size: 0.82rem;

                line-height: 1.45;
            }


            /* ----------------------------------------------- */
            /* Position Data Table                             */
            /* ----------------------------------------------- */

            /*
             * On mobile the dataframe is hidden.
             *
             * The responsive card representation is shown
             * instead.
             */

            .responsive-table-desktop {
                display: none !important;
            }

            .responsive-table-mobile {
                display: block !important;

                width: 100%;
                max-width: 100%;

                margin-top: 0.25rem;
            }


            /* ----------------------------------------------- */
            /* Position Data Cards                             */
            /* ----------------------------------------------- */

            .position-data-card {
                padding: 0.85rem 0.9rem;

                margin-bottom: 0.65rem;

                border-radius: 0.65rem;
            }

            .position-data-card-header {
                font-size: 0.76rem;

                margin-bottom: 0.4rem;
            }

            .position-data-card-value {
                font-size: 1.05rem;
            }

            .position-data-card-unit {
                font-size: 0.66rem;
            }

            .position-data-card-description {
                margin-top: 0.55rem;

                padding-top: 0.55rem;

                font-size: 0.73rem;

                line-height: 1.4;
            }


            /* ----------------------------------------------- */
            /* Footer                                          */
            /* ----------------------------------------------- */

            .footer {
                font-size: 0.72rem;

                margin-top: 1.5rem;
            }
        }


        /* ==================================================== */
        /* Very Small Phones                                    */
        /* ==================================================== */

        @media (max-width: 380px) {

            .block-container {
                padding-left: 0.55rem;
                padding-right: 0.55rem;
            }

            .input-introduction {
                padding: 0.75rem;
            }

            .input-introduction-title {
                font-size: 0.88rem;
            }

            .input-introduction-description {
                font-size: 0.76rem;
            }

            .input-introduction-note {
                font-size: 0.70rem;
            }

            .finding-card {
                padding: 0.75rem;
            }

            .finding-header {
                flex-direction: column;

                align-items: flex-start;
            }

            .finding-severity {
                align-self: flex-start;
            }

            .section-card {
                padding: 0.75rem;
            }

            .position-data-card {
                padding: 0.75rem;

                margin-bottom: 0.55rem;
            }

            .position-data-card-value {
                font-size: 1rem;
            }

            .position-data-card-description {
                font-size: 0.70rem;
            }
        }


        /* ==================================================== */
        /* Touch Devices                                        */
        /* ==================================================== */

        @media (hover: none) {

            .finding-card:hover {
                transform: none;

                border-color: var(--border);
            }
        }


        /* ==================================================== */
        /* Responsive Sidebar                                   */
        /* ==================================================== */

        @media (max-width: 768px) {

            [data-testid="stSidebar"] .block-container {
                padding-top: 1rem;

                padding-left: 0.85rem;
                padding-right: 0.85rem;

                padding-bottom: 1.5rem;
            }

            [data-testid="stSidebar"] h1 {
                font-size: 1.35rem;

                line-height: 1.2;
            }

            [data-testid="stSidebar"] h2 {
                font-size: 1.05rem;

                line-height: 1.25;
            }

            [data-testid="stSidebar"] h3 {
                font-size: 0.95rem;

                line-height: 1.3;
            }

            [data-testid="stSidebar"] p {
                line-height: 1.45;
            }

            [data-testid="stSidebar"] [role="radiogroup"] {
                width: 100%;
            }

            [data-testid="stSidebar"] [role="radiogroup"] label {
                width: 100%;

                min-width: 0;

                overflow-wrap: anywhere;
                word-break: break-word;
            }

            [data-testid="stSidebar"] {
                overflow-x: hidden;
            }

            [data-testid="stSidebar"] * {
                max-width: 100%;

                box-sizing: border-box;
            }

            [data-testid="stSidebar"] .badge {
                white-space: normal;

                word-break: break-word;
            }

            [data-testid="stSidebar"] .pipeline-legend {
                flex-direction: column;

                gap: 0.5rem;
            }

            [data-testid="stSidebar"] .pipeline-legend-item {
                min-width: 0;

                line-height: 1.35;
            }

            [data-testid="stSidebar"] .guarantee-item {
                width: 100%;

                min-width: 0;
            }

            [data-testid="stSidebar"] .guarantee-title {
                line-height: 1.35;
            }

            [data-testid="stSidebar"] .guarantee-description {
                display: block;

                margin-top: 0.2rem;

                line-height: 1.4;

                overflow-wrap: anywhere;
                word-break: break-word;
            }
        }


        </style>
        """,
        unsafe_allow_html=True,
    )
