import streamlit as st


# ============================================================
# Styling
# ============================================================
#
# Design language:
#
#   Deterministic
#       Blue accent. Used for rule-engine outputs and all
#       reproducible / traceable assessment information.
#
#   AI-assisted
#       Violet accent. Used for content generated by an LLM.
#
#   Fallback
#       Amber accent. Used when an LLM was requested but the
#       deterministic fallback generator was used.
#
# The CSS is intentionally responsive so that the application
# remains usable on desktop, tablet and mobile screens.
# ============================================================


def apply_styles() -> None:
    st.markdown(
        """
        <style>

        /* ==================================================== */
        /* Design Tokens                                        */
        /* ==================================================== */

        :root {
            --det-color: #2563eb;
            --det-bg: rgba(37, 99, 235, 0.08);

            --ai-color: #7c3aed;
            --ai-bg: rgba(124, 58, 237, 0.08);

            --fallback-color: #b45309;
            --fallback-bg: rgba(180, 83, 9, 0.10);

            --muted: #6b7280;
            --border: rgba(128, 128, 128, 0.20);

            --card-bg: rgba(128, 128, 128, 0.025);
            --radius: 0.75rem;
        }


        /* ==================================================== */
        /* Main Application Container                           */
        /* ==================================================== */

        .block-container {
            width: 100%;
            max-width: 1400px;

            padding-top: 1.6rem;
            padding-bottom: 3rem;

            padding-left: clamp(1rem, 3vw, 3rem);
            padding-right: clamp(1rem, 3vw, 3rem);
        }


        /* ==================================================== */
        /* Typography                                           */
        /* ==================================================== */

        h1,
        h2,
        h3 {
            letter-spacing: -0.01em;
        }

        .app-subtitle {
            color: var(--muted);

            font-size: 1rem;
            line-height: 1.5;

            margin-top: -0.4rem;
            margin-bottom: 1.2rem;
        }


        /* ==================================================== */
        /* Provenance Badges                                    */
        /* ==================================================== */

        .badge {
            display: inline-flex;
            align-items: center;

            gap: 0.35rem;

            max-width: 100%;

            padding: 0.22rem 0.65rem;

            border-radius: 999px;

            font-size: 0.75rem;
            font-weight: 650;

            letter-spacing: 0.01em;

            border: 1px solid transparent;

            white-space: normal;
            overflow-wrap: anywhere;
        }

        .badge-det {
            color: var(--det-color);

            background: var(--det-bg);

            border-color: rgba(37, 99, 235, 0.25);
        }

        .badge-ai {
            color: var(--ai-color);

            background: var(--ai-bg);

            border-color: rgba(124, 58, 237, 0.25);
        }

        .badge-fallback {
            color: var(--fallback-color);

            background: var(--fallback-bg);

            border-color: rgba(180, 83, 9, 0.28);
        }

        .badge-row {
            margin-bottom: 0.6rem;
        }


        /* ==================================================== */
        /* Pipeline / Workflow                                  */
        /* ==================================================== */

        .pipeline-wrap {
            display: flex;
            align-items: stretch;

            gap: 0.4rem;

            margin: 0.4rem 0 0.8rem 0;

            width: 100%;
        }

        .pipeline-step {
            flex: 1;
            min-width: 0;

            padding: 1rem 0.9rem;

            border-radius: var(--radius);

            border: 1.5px solid var(--border);

            background: var(--card-bg);

            min-height: 108px;

            position: relative;

            overflow-wrap: anywhere;
        }

        .pipeline-step.det {
            border-color: rgba(37, 99, 235, 0.35);

            background: var(--det-bg);
        }

        .pipeline-step.ai {
            border-color: rgba(124, 58, 237, 0.35);

            background: var(--ai-bg);
        }

        .pipeline-arrow {
            display: flex;
            align-items: center;
            justify-content: center;

            color: var(--muted);

            font-size: 1.1rem;

            padding: 0 0.1rem;

            flex-shrink: 0;
        }

        .pipeline-number {
            font-size: 0.72rem;

            font-weight: 750;

            color: var(--muted);

            letter-spacing: 0.06em;
        }

        .pipeline-title {
            font-weight: 650;

            margin-top: 0.25rem;

            font-size: 0.92rem;
        }

        .pipeline-description {
            color: var(--muted);

            font-size: 0.76rem;

            margin-top: 0.1rem;

            line-height: 1.35;
        }


        /* ==================================================== */
        /* Pipeline Legend                                      */
        /* ==================================================== */

        .pipeline-legend {
            display: flex;

            gap: 1.4rem;

            margin-top: 0.4rem;
            margin-bottom: 0.2rem;

            flex-wrap: wrap;
        }

        .pipeline-legend-item {
            display: flex;
            align-items: center;

            gap: 0.4rem;

            font-size: 0.78rem;

            color: var(--muted);

            min-width: 0;

            overflow-wrap: anywhere;
        }

        .legend-dot {
            width: 0.65rem;
            height: 0.65rem;

            min-width: 0.65rem;

            border-radius: 50%;

            display: inline-block;
        }

        .legend-dot.det {
            background: var(--det-color);
        }

        .legend-dot.ai {
            background: var(--ai-color);
        }


        /* ==================================================== */
        /* Generic Cards                                        */
        /* ==================================================== */

        .scenario-card {
            width: 100%;
            box-sizing: border-box;

            padding: 1.2rem 1.4rem;

            border-radius: var(--radius);

            border: 1px solid var(--border);

            background: var(--card-bg);

            margin-bottom: 1rem;

            overflow-wrap: anywhere;
        }

        .scenario-title {
            font-size: 1.1rem;

            font-weight: 650;

            margin-bottom: 0.4rem;
        }

        .scenario-description {
            color: var(--muted);

            font-size: 0.88rem;

            line-height: 1.5;
        }

        .data-introduction {
            color: var(--muted);

            font-size: 0.88rem;

            line-height: 1.5;

            margin-bottom: 1rem;
        }

        .data-note {
            width: 100%;
            box-sizing: border-box;

            padding: 0.9rem 1rem;

            border-radius: 0.6rem;

            border: 1px solid var(--border);

            background: var(--card-bg);

            margin-bottom: 1rem;

            font-size: 0.85rem;

            color: var(--muted);

            overflow-wrap: anywhere;
        }


        /* ==================================================== */
        /* Provenance Panel                                     */
        /* ==================================================== */

        .provenance-panel {
            width: 100%;
            box-sizing: border-box;

            border-radius: var(--radius);

            border: 1px solid var(--border);

            padding: 1.1rem 1.3rem;

            margin-bottom: 1.2rem;

            background: rgba(128, 128, 128, 0.02);

            overflow-wrap: anywhere;
        }

        .provenance-row {
            display: flex;
            align-items: center;
            justify-content: space-between;

            gap: 1rem;

            padding: 0.45rem 0;

            border-bottom: 1px dashed var(--border);

            font-size: 0.87rem;

            overflow-wrap: anywhere;
        }

        .provenance-row:last-child {
            border-bottom: none;
        }

        .provenance-label {
            color: inherit;

            font-weight: 550;
        }

        .metric-description {
            color: var(--muted);

            font-size: 0.78rem;

            line-height: 1.45;
        }


        /* ==================================================== */
        /* Section Cards                                        */
        /* ==================================================== */

        .section-card {
            width: 100%;
            box-sizing: border-box;

            border-radius: var(--radius);

            border: 1.5px solid var(--border);

            padding: 1rem 1.2rem;

            margin-bottom: 1rem;

            overflow-wrap: anywhere;
        }

        .section-card.det {
            border-left: 4px solid var(--det-color);
        }

        .section-card.ai {
            border-left: 4px solid var(--ai-color);
        }

        .section-card.fallback {
            border-left: 4px solid var(--fallback-color);
        }


        /* ==================================================== */
        /* Deterministic Finding Cards                          */
        /* ==================================================== */

        .finding-card {
            width: 100%;
            max-width: 100%;

            box-sizing: border-box;

            padding: 1rem 1.15rem;

            margin-bottom: 0.8rem;

            border-radius: var(--radius);

            border: 1px solid var(--border);

            background: var(--card-bg);

            overflow: hidden;

            transition:
                border-color 0.15s ease,
                transform 0.15s ease;
        }

        .finding-card:hover {
            border-color: rgba(37, 99, 235, 0.35);

            transform: translateY(-1px);
        }

        .finding-header {
            display: flex;

            align-items: center;
            justify-content: space-between;

            gap: 0.75rem;

            margin-bottom: 0.55rem;

            width: 100%;
        }

        .finding-rule {
            font-size: 0.82rem;

            font-weight: 750;

            letter-spacing: 0.04em;

            color: var(--det-color);

            min-width: 0;

            overflow-wrap: anywhere;
        }

        .finding-severity {
            flex-shrink: 0;

            padding: 0.18rem 0.55rem;

            border-radius: 999px;

            font-size: 0.70rem;

            font-weight: 700;

            text-transform: uppercase;

            letter-spacing: 0.04em;

            color: var(--det-color);

            background: var(--det-bg);

            border: 1px solid rgba(37, 99, 235, 0.25);
        }

        .finding-severity.high,
        .finding-severity.critical {
            color: var(--fallback-color);

            background: var(--fallback-bg);

            border-color: rgba(180, 83, 9, 0.28);
        }

        .finding-category {
            font-size: 0.78rem;

            font-weight: 700;

            letter-spacing: 0.04em;

            margin-bottom: 0.4rem;

            color: inherit;

            overflow-wrap: anywhere;
        }

        .finding-description {
            color: var(--muted);

            font-size: 0.86rem;

            line-height: 1.5;

            overflow-wrap: anywhere;

            word-break: break-word;
        }


        /* ==================================================== */
        /* Guarantee Items                                      */
        /* ==================================================== */

        .guarantee-item {
            width: 100%;

            box-sizing: border-box;

            padding: 0.55rem 0;

            border-bottom: 1px dashed var(--border);
        }

        .guarantee-item:last-child {
            border-bottom: none;
        }

        .guarantee-title {
            font-weight: 600;

            font-size: 0.86rem;

            line-height: 1.35;

            overflow-wrap: anywhere;
        }

        .guarantee-description {
            display: block;

            margin-top: 0.2rem;

            line-height: 1.4;

            overflow-wrap: anywhere;
        }


        /* ==================================================== */
        /* Footer                                               */
        /* ==================================================== */

        .footer {
            margin-top: 2rem;

            padding-top: 1rem;

            border-top: 1px solid var(--border);

            color: var(--muted);

            font-size: 0.78rem;

            line-height: 1.5;

            overflow-wrap: anywhere;
        }


        /* ==================================================== */
        /* Tablet                                               */
        /* ==================================================== */

        @media (max-width: 900px) {

            .block-container {
                padding-top: 1.2rem;

                padding-bottom: 2rem;

                padding-left: 1rem;
                padding-right: 1rem;
            }

            .pipeline-wrap {
                flex-wrap: wrap;
            }

            .pipeline-step {
                flex: 1 1 calc(50% - 0.4rem);

                min-width: 220px;
            }

            .pipeline-arrow {
                display: none;
            }

            .section-card {
                padding: 0.9rem 1rem;
            }

            .scenario-card {
                padding: 1rem;
            }
        }


        /* ==================================================== */
        /* Mobile                                               */
        /* ==================================================== */

        @media (max-width: 640px) {

            /* ----------------------------------------------- */
            /* Main container                                  */
            /* ----------------------------------------------- */

            .block-container {
                padding-top: 0.8rem;

                padding-bottom: 1.5rem;

                padding-left: 0.75rem;
                padding-right: 0.75rem;
            }


            /* ----------------------------------------------- */
            /* Typography                                      */
            /* ----------------------------------------------- */

            .app-subtitle {
                font-size: 0.88rem;

                margin-top: -0.2rem;

                margin-bottom: 1rem;
            }


            /* ----------------------------------------------- */
            /* Badges                                          */
            /* ----------------------------------------------- */

            .badge {
                font-size: 0.70rem;

                padding: 0.20rem 0.55rem;

                white-space: normal;

                line-height: 1.35;

                overflow-wrap: anywhere;
            }


            /* ----------------------------------------------- */
            /* Pipeline                                        */
            /* ----------------------------------------------- */

            .pipeline-wrap {
                display: flex;

                flex-direction: column;

                gap: 0.6rem;
            }

            .pipeline-step {
                flex: none;

                width: 100%;

                min-width: 0;

                min-height: auto;

                padding: 0.85rem;
            }

            .pipeline-arrow {
                display: none;
            }

            .pipeline-title {
                font-size: 0.88rem;
            }

            .pipeline-description {
                font-size: 0.75rem;
            }


            /* ----------------------------------------------- */
            /* Legend                                          */
            /* ----------------------------------------------- */

            .pipeline-legend {
                flex-direction: column;

                gap: 0.5rem;
            }

            .pipeline-legend-item {
                font-size: 0.75rem;
            }


            /* ----------------------------------------------- */
            /* Generic cards                                   */
            /* ----------------------------------------------- */

            .scenario-card {
                padding: 0.9rem;

                border-radius: 0.65rem;
            }

            .scenario-title {
                font-size: 1rem;
            }

            .scenario-description,
            .data-introduction {
                font-size: 0.84rem;
            }

            .data-note {
                padding: 0.8rem;

                font-size: 0.80rem;
            }


            /* ----------------------------------------------- */
            /* Provenance                                      */
            /* ----------------------------------------------- */

            .provenance-panel {
                padding: 0.9rem;
            }

            .provenance-row {
                flex-direction: column;

                align-items: flex-start;

                gap: 0.35rem;
            }


            /* ----------------------------------------------- */
            /* Section cards                                   */
            /* ----------------------------------------------- */

            .section-card {
                padding: 0.85rem 0.9rem;

                margin-bottom: 0.75rem;
            }


            /* ----------------------------------------------- */
            /* Finding cards                                   */
            /* ----------------------------------------------- */

            .finding-card {
                padding: 0.85rem;

                border-radius: 0.65rem;

                margin-bottom: 0.65rem;
            }

            .finding-header {
                align-items: flex-start;

                gap: 0.5rem;

                margin-bottom: 0.5rem;
            }

            .finding-rule {
                font-size: 0.78rem;
            }

            .finding-severity {
                font-size: 0.64rem;

                padding: 0.16rem 0.45rem;
            }

            .finding-category {
                font-size: 0.72rem;
            }

            .finding-description {
                font-size: 0.82rem;

                line-height: 1.45;
            }


            /* ----------------------------------------------- */
            /* Footer                                          */
            /* ----------------------------------------------- */

            .footer {
                font-size: 0.72rem;

                margin-top: 1.5rem;
            }
        }


        /* ==================================================== */
        /* Very Small Phones                                    */
        /* ==================================================== */

        @media (max-width: 380px) {

            .block-container {
                padding-left: 0.55rem;

                padding-right: 0.55rem;
            }

            .finding-card {
                padding: 0.75rem;
            }

            .finding-header {
                flex-direction: column;

                align-items: flex-start;
            }

            .finding-severity {
                align-self: flex-start;
            }

            .section-card {
                padding: 0.75rem;
            }
        }


        /* ==================================================== */
        /* Touch Devices                                        */
        /* ==================================================== */

        @media (hover: none) {

            .finding-card:hover {
                transform: none;

                border-color: var(--border);
            }
        }


        /* ==================================================== */
        /* Responsive Sidebar                                   */
        /* ==================================================== */

        @media (max-width: 768px) {

            /* ----------------------------------------------- */
            /* Sidebar container                               */
            /* ----------------------------------------------- */

            [data-testid="stSidebar"] .block-container {
                padding-top: 1rem;

                padding-left: 0.85rem;
                padding-right: 0.85rem;

                padding-bottom: 1.5rem;
            }


            /* ----------------------------------------------- */
            /* Sidebar headings                                 */
            /* ----------------------------------------------- */

            [data-testid="stSidebar"] h1 {
                font-size: 1.35rem;

                line-height: 1.2;
            }

            [data-testid="stSidebar"] h2 {
                font-size: 1.05rem;

                line-height: 1.25;
            }

            [data-testid="stSidebar"] h3 {
                font-size: 0.95rem;

                line-height: 1.3;
            }


            /* ----------------------------------------------- */
            /* Sidebar text                                     */
            /* ----------------------------------------------- */

            [data-testid="stSidebar"] p {
                line-height: 1.45;
            }


            /* ----------------------------------------------- */
            /* Radio options                                    */
            /* ----------------------------------------------- */

            [data-testid="stSidebar"] [role="radiogroup"] {
                width: 100%;
            }

            [data-testid="stSidebar"] [role="radiogroup"] label {
                width: 100%;

                min-width: 0;
            }


            /* ----------------------------------------------- */
            /* Prevent horizontal overflow                      */
            /* ----------------------------------------------- */

            [data-testid="stSidebar"] {
                overflow-x: hidden;
            }

            [data-testid="stSidebar"] * {
                max-width: 100%;

                box-sizing: border-box;
            }


            /* ----------------------------------------------- */
            /* Badges                                           */
            /* ----------------------------------------------- */

            [data-testid="stSidebar"] .badge {
                white-space: normal;

                word-break: break-word;
            }


            /* ----------------------------------------------- */
            /* Legend                                           */
            /* ----------------------------------------------- */

            [data-testid="stSidebar"] .pipeline-legend {
                flex-direction: column;

                gap: 0.5rem;
            }

            [data-testid="stSidebar"] .pipeline-legend-item {
                min-width: 0;

                line-height: 1.35;
            }


            /* ----------------------------------------------- */
            /* Architecture guarantees                          */
            /* ----------------------------------------------- */

            [data-testid="stSidebar"] .guarantee-item {
                width: 100%;

                min-width: 0;
            }

            [data-testid="stSidebar"] .guarantee-title {
                line-height: 1.35;
            }

            [data-testid="stSidebar"] .guarantee-description {
                display: block;

                margin-top: 0.2rem;

                line-height: 1.4;

                overflow-wrap: anywhere;
            }
        }


        </style>
        """,
        unsafe_allow_html=True,
    )