# AnalysisAgent tests

import pytest

from src.agents.analysis.analysis_agent import AnalysisAgent
from src.agents.base.agent import Agent
from src.comments.comment import Comment
from src.models.analysis_finding import AnalysisFinding
from src.models.assessment import Assessment
from src.models.assessment_analysis import AssessmentAnalysis
from src.models.assessment_status import AssessmentStatus
from src.models.rule_finding import RuleFinding
from src.rules.base.severity import RuleSeverity
from src.rules.base.status import RuleStatus
from src.rules.result import RuleResult


@pytest.fixture
def analysis_agent():
    return AnalysisAgent()


def make_rule_result(
    *,
    rule_id: str = "TEST_RULE",
    rule_name: str = "Test rule",
    category: str = "TEST_CATEGORY",
    status: RuleStatus = RuleStatus.TRIGGERED,
    severity: RuleSeverity = RuleSeverity.HIGH,
    value: float | None = None,
    threshold: float | None = None,
) -> RuleResult:
    return RuleResult(
        rule_id=rule_id,
        rule_name=rule_name,
        category=category,
        status=status,
        value=value,
        threshold=threshold,
        severity=severity,
    )


def make_finding(
    result: RuleResult,
    text: str | None = None,
) -> RuleFinding:
    return RuleFinding(
        result=result,
        comment=Comment(
            rule_id=result.rule_id,
            text=text or f"Finding for {result.rule_id}.",
        ),
    )


def make_assessment(
    *,
    position_id: str = "TEST_POSITION",
    status: AssessmentStatus = AssessmentStatus.ATTENTION,
    rule_results: list[RuleResult] | None = None,
    findings: list[RuleFinding] | None = None,
) -> Assessment:
    return Assessment(
        position_id=position_id,
        status=status,
        rule_results=rule_results or [],
        findings=findings or [],
    )


def test_analysis_agent_implements_agent_contract(
    analysis_agent,
):
    assert isinstance(analysis_agent, Agent)


def test_analysis_agent_produces_structured_analysis(
    analysis_agent,
):
    triggered_results = [
        make_rule_result(
            rule_id=f"TRIGGERED_{index}",
            category=f"CATEGORY_{index}",
            severity=severity,
        )
        for index, severity in enumerate(
            [RuleSeverity.HIGH, RuleSeverity.MEDIUM],
            start=1,
        )
    ]

    not_evaluable_result = make_rule_result(
        rule_id="NOT_EVALUABLE",
        rule_name="Unavailable metric",
        category="UNAVAILABLE_CATEGORY",
        status=RuleStatus.NOT_EVALUABLE,
        severity=RuleSeverity.MEDIUM,
    )

    findings = [make_finding(result) for result in triggered_results]

    assessment = make_assessment(
        status=AssessmentStatus.CRITICAL,
        rule_results=[
            *triggered_results,
            not_evaluable_result,
        ],
        findings=findings,
    )

    analysis = analysis_agent.run(assessment)

    assert isinstance(analysis, AssessmentAnalysis)
    assert analysis.position_id == assessment.position_id
    assert analysis.assessment_status == assessment.status

    assert all(
        isinstance(finding, AnalysisFinding) for finding in analysis.key_findings
    )

    expected_findings = [
        (
            finding.comment.text,
            finding.result.rule_id,
            finding.result.category,
            finding.result.severity,
        )
        for finding in findings
    ]

    actual_findings = [
        (
            finding.text,
            finding.rule_id,
            finding.category,
            finding.severity,
        )
        for finding in analysis.key_findings
    ]

    assert actual_findings == expected_findings

    expected_risk_factors = [
        finding
        for finding in analysis.key_findings
        if finding.severity == RuleSeverity.HIGH
    ]

    assert analysis.risk_factors == expected_risk_factors

    expected_limitations = [
        (
            f"{result.rule_name} could not be evaluated.",
            result.rule_id,
            result.category,
            result.severity,
        )
        for result in [not_evaluable_result]
    ]

    actual_limitations = [
        (
            finding.text,
            finding.rule_id,
            finding.category,
            finding.severity,
        )
        for finding in analysis.limitations
    ]

    assert actual_limitations == expected_limitations


def test_analysis_agent_preserves_comment_text(
    analysis_agent,
):
    result = make_rule_result(
        rule_id="ARBITRARY_RULE",
        category="ARBITRARY_CATEGORY",
        severity=RuleSeverity.MEDIUM,
    )

    comment_text = "Custom finding generated by the comment engine."

    assessment = make_assessment(
        rule_results=[result],
        findings=[
            make_finding(
                result,
                comment_text,
            )
        ],
    )

    analysis = analysis_agent.run(assessment)

    assert len(analysis.key_findings) == 1

    finding = analysis.key_findings[0]

    assert finding.text == comment_text
    assert finding.rule_id == result.rule_id
    assert finding.category == result.category
    assert finding.severity == result.severity


def test_analysis_agent_does_not_depend_on_rule_ids(
    analysis_agent,
):
    results = [
        make_rule_result(
            rule_id="ARBITRARY_ID_A",
            category="CATEGORY_A",
            severity=RuleSeverity.HIGH,
        ),
        make_rule_result(
            rule_id="COMPLETELY_DIFFERENT_ID",
            category="CATEGORY_B",
            severity=RuleSeverity.MEDIUM,
        ),
    ]

    findings = [make_finding(result) for result in results]

    assessment = make_assessment(
        rule_results=results,
        findings=findings,
    )

    analysis = analysis_agent.run(assessment)

    assert analysis.assessment_status == assessment.status

    assert [finding.rule_id for finding in analysis.key_findings] == [
        result.rule_id for result in results
    ]

    assert [finding.category for finding in analysis.key_findings] == [
        result.category for result in results
    ]

    assert [finding.text for finding in analysis.key_findings] == [
        finding.comment.text for finding in findings
    ]

    assert [finding.rule_id for finding in analysis.risk_factors] == [
        results[0].rule_id
    ]


def test_analysis_agent_ignores_not_triggered_rules(
    analysis_agent,
):
    triggered_result = make_rule_result(
        status=RuleStatus.TRIGGERED,
        severity=RuleSeverity.HIGH,
    )

    not_triggered_result = make_rule_result(
        rule_id="NOT_TRIGGERED",
        status=RuleStatus.NOT_TRIGGERED,
        severity=RuleSeverity.LOW,
    )

    triggered_finding = make_finding(triggered_result)

    assessment = make_assessment(
        rule_results=[
            triggered_result,
            not_triggered_result,
        ],
        findings=[triggered_finding],
    )

    analysis = analysis_agent.run(assessment)

    assert [finding.rule_id for finding in analysis.key_findings] == [
        triggered_result.rule_id
    ]

    assert [finding.rule_id for finding in analysis.risk_factors] == [
        triggered_result.rule_id
    ]

    assert analysis.limitations == []


def test_analysis_agent_handles_assessment_without_triggered_rules(
    analysis_agent,
):
    results = [
        make_rule_result(
            rule_id=f"RULE_{index}",
            status=RuleStatus.NOT_TRIGGERED,
            severity=RuleSeverity.LOW,
        )
        for index in range(2)
    ]

    assessment = make_assessment(
        status=AssessmentStatus.NORMAL,
        rule_results=results,
        findings=[],
    )

    analysis = analysis_agent.run(assessment)

    assert analysis.position_id == assessment.position_id
    assert analysis.assessment_status == assessment.status
    assert analysis.key_findings == []
    assert analysis.risk_factors == []
    assert analysis.limitations == []


def test_analysis_agent_reports_not_evaluable_rules_as_limitations(
    analysis_agent,
):
    results = [
        make_rule_result(
            rule_id=f"UNAVAILABLE_{index}",
            rule_name=f"Unavailable metric {index}",
            category=f"CATEGORY_{index}",
            status=RuleStatus.NOT_EVALUABLE,
            severity=severity,
        )
        for index, severity in enumerate(
            [RuleSeverity.MEDIUM, RuleSeverity.LOW],
            start=1,
        )
    ]

    assessment = make_assessment(
        status=AssessmentStatus.NORMAL,
        rule_results=results,
        findings=[],
    )

    analysis = analysis_agent.run(assessment)

    assert analysis.key_findings == []
    assert analysis.risk_factors == []

    expected_limitations = [
        (
            f"{result.rule_name} could not be evaluated.",
            result.rule_id,
            result.category,
            result.severity,
        )
        for result in results
    ]

    actual_limitations = [
        (
            finding.text,
            finding.rule_id,
            finding.category,
            finding.severity,
        )
        for finding in analysis.limitations
    ]

    assert actual_limitations == expected_limitations


@pytest.mark.parametrize(
    "severity, expected_as_risk_factor",
    [
        (RuleSeverity.HIGH, True),
        (RuleSeverity.MEDIUM, False),
        (RuleSeverity.LOW, False),
    ],
)
def test_analysis_agent_selects_high_severity_risk_factors(
    analysis_agent,
    severity,
    expected_as_risk_factor,
):
    result = make_rule_result(
        severity=severity,
    )

    finding = make_finding(result)

    assessment = make_assessment(
        status=AssessmentStatus.CRITICAL,
        rule_results=[result],
        findings=[finding],
    )

    analysis = analysis_agent.run(assessment)

    assert len(analysis.key_findings) == 1
    assert analysis.key_findings[0].text == finding.comment.text

    expected_risk_factors = analysis.key_findings if expected_as_risk_factor else []

    assert analysis.risk_factors == expected_risk_factors
