"""Presentation metadata and formatting for CreditPosition fields.

This module contains no Streamlit rendering and no credit-assessment logic.
The CreditPosition dataclass remains the source of truth for the input schema.
"""

from dataclasses import MISSING, fields
from types import UnionType
from typing import Any, get_args, get_origin, get_type_hints

from src.models.position import CreditPosition


def get_credit_position_fields():
    """Return the fields defined by the CreditPosition dataclass."""
    return fields(CreditPosition)


def get_credit_position_type_hints() -> dict[str, Any]:
    """Return resolved type annotations for CreditPosition."""
    return get_type_hints(CreditPosition)


def get_field_default(field) -> Any:
    """Return the dataclass default, or None when no default is defined."""
    if field.default is not MISSING:
        return field.default

    if field.default_factory is not MISSING:
        return field.default_factory()

    return None


def unwrap_optional(field_type: Any) -> tuple[Any, bool]:
    """Resolve Optional / Union-with-None annotations."""
    origin = get_origin(field_type)
    args = get_args(field_type)

    if origin is UnionType:
        non_none_types = [argument for argument in args if argument is not type(None)]
        if len(non_none_types) == 1:
            return non_none_types[0], True

    if args and type(None) in args:
        non_none_types = [argument for argument in args if argument is not type(None)]
        if len(non_none_types) == 1:
            return non_none_types[0], True

    return field_type, False


def format_field_label(field_name: str) -> str:
    """Convert a CreditPosition field name into a human-readable label."""
    special_terms = {
        "ebitda": "EBITDA",
        "nfp": "NFP",
        "ews": "EWS",
        "id": "ID",
    }

    words = field_name.split("_")
    formatted_words = []

    for word in words:
        if word.lower() in special_terms:
            formatted_words.append(special_terms[word.lower()])
        else:
            formatted_words.append(word.capitalize())

    return " ".join(formatted_words)


FIELD_DESCRIPTIONS: dict[str, str] = {
    "position_id": "Unique identifier of the credit position.",
    "revenue": "Total company revenue.",
    "change_in_finished_goods_inventory": "Change in finished goods inventory.",
    "operating_grants": "Operating grants received by the company.",
    "net_purchases": "Net purchases of raw materials and goods.",
    "change_in_raw_materials_inventory": "Change in raw materials inventory.",
    "costs_for_services_and_third_party_assets": (
        "Costs related to services and third-party assets."
    ),
    "personnel_costs": "Personnel and employee-related costs.",
    "depreciation_tangible_assets": "Depreciation of tangible fixed assets.",
    "working_capital_impairments": "Impairments related to working capital.",
    "operating_provisions": "Operating provisions and related adjustments.",
    "other_income_expenses_balance": (
        "Net balance of other operating income and expenses."
    ),
    "operating_value_added": "Derived operating value added.",
    "gross_operating_margin": "Gross operating margin generated by the company.",
    "net_operating_margin": "Net operating margin after operating costs.",
    "ebitda": "Earnings before interest, taxes, depreciation and amortization.",
    "profit_loss": "Reported profit or loss for the company.",
    "ebitda_margin": "EBITDA expressed as a percentage of revenue.",
    "ebitda_inventory_contribution": "Contribution of inventory changes to EBITDA.",
    "nfp_to_ebitda": (
        "Net financial position relative to EBITDA; a leverage indicator."
    ),
    "interest_expense": "Financial expense related to interest.",
    "revenue_growth": "Year-over-year change in company revenue.",
    "ews_score_class": (
        "Early Warning System score class: GREEN, YELLOW, ORANGE or LIGHT_RED."
    ),
}


def format_field_description(field_name: str) -> str:
    """Return the display description for a CreditPosition field."""
    return FIELD_DESCRIPTIONS.get(
        field_name,
        f"Input value for {format_field_label(field_name)}.",
    )


PERCENTAGE_FIELDS = {
    "revenue_growth",
    "ebitda_margin",
}

CURRENCY_FIELDS = {
    "revenue",
    "change_in_finished_goods_inventory",
    "operating_grants",
    "net_purchases",
    "change_in_raw_materials_inventory",
    "costs_for_services_and_third_party_assets",
    "personnel_costs",
    "depreciation_tangible_assets",
    "working_capital_impairments",
    "operating_provisions",
    "other_income_expenses_balance",
    "operating_value_added",
    "gross_operating_margin",
    "net_operating_margin",
    "ebitda",
    "profit_loss",
    "ebitda_inventory_contribution",
    "interest_expense",
}


def format_field_value(field_name: str, value: Any) -> str:
    """Format a field value for display without changing its underlying value."""
    if value is None:
        return "Not available"

    if field_name == "position_id":
        return str(value)

    if field_name in PERCENTAGE_FIELDS:
        return f"{float(value):.1%}"

    if field_name in CURRENCY_FIELDS:
        return f"€{float(value):,.0f}"

    if field_name == "nfp_to_ebitda":
        return f"{float(value):.2f}x"

    if isinstance(value, float):
        return f"{value:,.4f}"

    return str(getattr(value, "value", value))


FIELD_UNITS: dict[str, str] = {
    "position_id": "Identifier",
    "revenue_growth": "%",
    "ebitda_margin": "%",
    "revenue": "EUR",
    "change_in_finished_goods_inventory": "EUR",
    "operating_grants": "EUR",
    "net_purchases": "EUR",
    "change_in_raw_materials_inventory": "EUR",
    "costs_for_services_and_third_party_assets": "EUR",
    "personnel_costs": "EUR",
    "depreciation_tangible_assets": "EUR",
    "working_capital_impairments": "EUR",
    "operating_provisions": "EUR",
    "other_income_expenses_balance": "EUR",
    "operating_value_added": "EUR",
    "gross_operating_margin": "EUR",
    "net_operating_margin": "EUR",
    "ebitda": "EUR",
    "profit_loss": "EUR",
    "ebitda_inventory_contribution": "EUR",
    "interest_expense": "EUR",
    "nfp_to_ebitda": "x",
}


def get_field_unit(field_name: str) -> str:
    """Return the display unit for a CreditPosition field."""
    return FIELD_UNITS.get(field_name, "")


def build_scenario_data_table(
    position: CreditPosition,
) -> list[dict[str, str]]:
    """Build the display table for a CreditPosition without rendering it."""
    rows = []

    for field in fields(position):
        field_name = field.name
        value = getattr(position, field_name)

        rows.append(
            {
                "Financial Indicator": format_field_label(field_name),
                "Value": format_field_value(field_name, value),
                "Unit": get_field_unit(field_name),
                "Description": format_field_description(field_name),
            }
        )

    return rows


FIELD_GROUPS: dict[str, list[str]] = {
    "Identification": [
        "position_id",
    ],
    "Financial Performance": [
        "revenue",
        "revenue_growth",
        "ebitda",
        "ebitda_margin",
        "profit_loss",
    ],
    "Operating Data": [
        "change_in_finished_goods_inventory",
        "operating_grants",
        "net_purchases",
        "change_in_raw_materials_inventory",
        "costs_for_services_and_third_party_assets",
        "personnel_costs",
        "depreciation_tangible_assets",
        "working_capital_impairments",
        "operating_provisions",
        "other_income_expenses_balance",
        "operating_value_added",
        "gross_operating_margin",
        "net_operating_margin",
        "ebitda_inventory_contribution",
    ],
    "Leverage & Financial Structure": [
        "nfp_to_ebitda",
        "interest_expense",
    ],
}
